import fs from "node:fs";
import path from "node:path";
import { loadCategoriesDsl } from "../dsl/loadCategoriesDsl";

/**
 * Génère les règles de redirection Caddy avec la syntaxe map
 */
function generateCaddy() {
  const dsl = loadCategoriesDsl(path.join(__dirname, "../categories.dsl.yaml"));

  const lines: string[] = [];

  lines.push("# AUTOGENERATED FILE — DO NOT EDIT");
  lines.push("# Old categories redirections");
  lines.push("# Using {http.request.orig_uri.path} because {path} matches /index.html");
  lines.push(
    'map {http.request.orig_uri.path} {category_source} {category_target_path} {'
  );

  // Collecter toutes les redirections
  const redirections: Array<{ oldSlug: string; newSlug: string }> = [];

  for (const [, category] of Object.entries(dsl.categories)) {
    for (const entry of category.history) {
      // Si l'entrée a un `until`, ça veut dire que c'est un ancien slug
      if (entry.until) {
        redirections.push({
          oldSlug: entry.slug,
          newSlug: category.slug,
        });
      }
    }
  }

  // Trier par ordre alphabétique du oldSlug pour la lisibilité
  redirections.sort((a, b) => a.oldSlug.localeCompare(b.oldSlug));

  // Générer les lignes de redirection
  for (const { oldSlug, newSlug } of redirections) {
    lines.push(
      `\t~^(.*/search/.*)/(${oldSlug})(.*)$ "\${2}" "\${1}/${newSlug}\${3}"`
    );
  }

  lines.push("}");

  const outputPath = path.join(
    __dirname,
    "../generated/category-redirects.caddy"
  );

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n") + "\n");

  console.log("✅ Caddy file generated");
}

generateCaddy();
