export enum CampaignSource {
  CALL = "CALL",
  CONTACT = "CONTACT",
  COORDINATION = "COORDINATION",
  INTERNET = "INTERNET",
  EMAIL = "EMAIL",
  EMAILS_AUTOMATIQUES = "EMAILS_AUTOMATIQUES",
  CHAT = "CHAT",
  VISIT = "VISIT",
}
