import { CampaignInfos } from "../types/CampaignInfos.type";
import { CampaignChangesSection } from "../enums/CampaignChangesSection.enum";
import { CampaignName } from "../enums/CampaignName.enum";
import { CountryCodes } from "../../location/enums/CountryCodes.enum";
import { DEPARTMENT_CODES } from "../../location/constants/ALL_DEPARTMENT_CODES.const";
import { PlaceType } from "../../place/enums/PlaceType.enum";

/**
 * @deprecated Les campagnes sont désormais persistées dans la collection
 * `campaigns` (interface `Campaign`) et ne sont plus hardcodées ici.
 * Ce mapping est conservé pour les crisis campaigns actives / historiques.
 */
export const CAMPAIGN_LIST: { [key in CampaignName]: CampaignInfos } = {
  MAJ_ETE_2022: {
    adjective: "estivale",
    closingFormula: "Bel été",
    dateDebutAffichage: new Date("2022-07-07T00:00:00.000Z"),
    dateDebutCampagne: new Date("2022-06-07T10:00:00.000Z"),
    dateFin: new Date("2022-09-01T00:00:00.000Z"),
    icon: "sun",
    name: "SUMMER",
    period: "juillet-août",
    placesToUpdate: { placeType: PlaceType.PLACE },
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2022,
  },
  MAJ_ETE_2023: {
    adjective: "estivale",
    closingFormula: "Bel été",
    dateDebutAffichage: new Date("2023-07-15T00:00:00.000Z"),
    dateDebutCampagne: new Date("2023-05-28T10:00:00.000Z"),
    dateFin: new Date("2023-09-01T00:00:00.000Z"),
    icon: "sun",
    name: "SUMMER",
    period: "juillet-août",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "SPECIFIC_SERVICE_FOR_HEATWAVES",
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2023,
  },
  MAJ_ETE_2024: {
    adjective: "estivale",
    closingFormula: "Bel été",
    dateDebutAffichage: new Date("2024-08-01T00:00:00.000Z"),
    dateDebutCampagne: new Date("2024-06-04T00:00:00.000Z"),
    dateFin: new Date("2024-09-01T00:00:00.000Z"),
    icon: "sun",
    name: "SUMMER",
    period: "juillet-août",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "SPECIFIC_SERVICE_FOR_HEATWAVES",
    territories: DEPARTMENT_CODES[CountryCodes.FR].filter(
      (code) => code !== "974"
    ),
    year: 2024,
  },
  MAJ_HIVER_2022: {
    adjective: "hivernale",
    closingFormula: "Bonnes fêtes de fin d'année",
    dateDebutAffichage: new Date("2022-12-19T00:00:00.000Z"),
    dateDebutCampagne: new Date("2022-11-07T01:00:00.000Z"),
    dateFin: new Date("2023-01-02T00:00:00.000Z"),
    icon: "snow",
    name: "WINTER",
    period: "décembre-janvier",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2022,
  },
  MAJ_HIVER_2023: {
    adjective: "hivernale",
    closingFormula: "Bonnes fêtes de fin d'année",
    dateDebutAffichage: new Date("2023-12-19T00:00:00.000Z"),
    dateDebutCampagne: new Date("2023-11-04T01:00:00.000Z"),
    dateFin: new Date("2023-12-31T00:00:00.000Z"),
    icon: "snow",
    name: "WINTER",
    period: "décembre-janvier",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "SPECIFIC_SERVICE_FOR_WINTER",
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2023,
  },
  END_YEAR_2024: {
    closingFormula: "Bonne fin d'année",
    dateDebutAffichage: new Date("2024-12-20T00:00:00.000Z"),
    dateDebutCampagne: new Date("2024-11-04T00:00:00.000Z"),
    dateFin: new Date("2025-01-05T00:00:00.000Z"),
    name: "END_OF_YEAR",
    period: "décembre-janvier",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "",
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2024,
  },
  MID_YEAR_2025: {
    closingFormula: "Bonne fin d'année",
    dateDebutAffichage: new Date("2025-08-01T00:00:00.000Z"),
    dateDebutCampagne: new Date("2025-06-10T00:00:00.000Z"),
    dateFin: new Date("2025-08-31T00:00:00.000Z"),
    name: "MID_YEAR",
    period: "juin-juillet",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "",
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2025,
  },
  END_YEAR_2025: {
    closingFormula: "Bonne fin d'année",
    dateDebutAffichage: new Date("2025-12-20T00:00:00.000Z"),
    dateDebutCampagne: new Date("2025-11-06T00:00:00.000Z"),
    dateFin: new Date("2026-01-04T00:00:00.000Z"),
    name: "END_OF_YEAR",
    period: "décembre-janvier",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "",
    territories: [...DEPARTMENT_CODES[CountryCodes.FR]],
    year: 2025,
  },
  MID_YEAR_2026: {
    adjective: "estivale",
    closingFormula: "Bel été",
    dateDebutAffichage: new Date("2026-07-15T00:00:00.000Z"),
    dateDebutCampagne: new Date("2026-05-28T00:00:00.000Z"),
    dateFin: new Date("2026-08-31T23:59:59.000Z"),
    icon: "sun",
    name: "MID_YEAR",
    period: "juin-août",
    placesToUpdate: null,
    sections: [
      CampaignChangesSection.tempClosure,
      CampaignChangesSection.services,
      CampaignChangesSection.tempHours,
      CampaignChangesSection.tempMessage,
    ],
    specificServiceMessage: "",
    territories: [
      ...DEPARTMENT_CODES[CountryCodes.FR],
      ...DEPARTMENT_CODES[CountryCodes.ES],
      ...DEPARTMENT_CODES[CountryCodes.AD],
    ],
    year: 2026,
  },
};
