export enum PlaceChangesSection {
  CAMPAIGN_SOURCE_MAJ = "CAMPAIGN_SOURCE_MAJ",
  contacts = "contacts",
  generalinfo = "generalinfo",
  emplacement = "emplacement",
  hours = "hours",
  modalities = "modalities",
  new = "new",
  place = "place",
  public = "public",
  photos = "photos",
  remindMe = "remindMe",
  services = "services",
  status = "status",
  sources = "sources",
  tempClosure = "tempClosure",
  tempHours = "tempHours",
  tempMessage = "tempMessage",
  visibility = "visibility",
}
