/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import { z } from 'zod';
import { v20260101SearchRequestSchema } from './2026-01-01/search.request/2026-01-01.search.request.generated';
import { v20260101SearchResponseSchema } from './2026-01-01/search.response/2026-01-01.search.response.generated';
import { v20260303SearchRequestSchema } from './2026-03-03/search.request/2026-03-03.search.request.generated';
import { v20260303SearchResponseSchema } from './2026-03-03/search.response/2026-03-03.search.response.generated';

type ApiVersion = `${number}-${number}-${number}`;

export const requestSchemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny> = new Map<ApiVersion, z.ZodTypeAny>(
[
  ['2026-01-01', v20260101SearchRequestSchema] as [ApiVersion, z.ZodTypeAny],
  ['2026-03-03', v20260303SearchRequestSchema] as [ApiVersion, z.ZodTypeAny],
]);

export const responseSchemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny> = new Map<ApiVersion, z.ZodTypeAny>(
[
  ['2026-01-01', v20260101SearchResponseSchema] as [ApiVersion, z.ZodTypeAny],
  ['2026-03-03', v20260303SearchResponseSchema] as [ApiVersion, z.ZodTypeAny],
]);
