/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import { z } from 'zod';

export const v20260303SearchRequestSchema = z
  .looseObject({
    categories: z.array(z.string()).optional(),
    q: z.string().nullable().optional(),
    language: z.string().nullable().optional(),
    location: z
      .object({
        country: z.string().optional(),
        administrativeDivision: z
          .object({
            regionCode: z.string().optional(),
            region: z.string().optional(),
            departmentCode: z.string().optional(),
            department: z.string().optional(),
          })
          .optional(),
        city: z
          .object({
            type: z.enum(['city', 'postalCode']).optional(),
            value: z.string().optional(),
          })
          .optional(),
        coordinates: z
          .object({
            latitude: z.number().optional(),
            longitude: z.number().optional(),
          })
          .optional(),
        radiusKm: z.number().optional(),
      })
      .optional(),
    availability: z
      .object({
        openToday: z.boolean().optional(),
      })
      .optional(),
    access: z
      .object({
        kind: z.enum(['unconditional', 'conditional']).optional(),
        modes: z
          .array(z.enum(['appointment', 'registration', 'orientation']))
          .optional(),
      })
      .optional(),
    audience: z
      .object({
        admissionPolicy: z.enum(['open', 'restricted']).optional(),
        isTargeted: z.boolean().optional(),
        administrativeStatuses: z.array(z.string()).optional(),
        age: z
          .object({
            min: z.number().optional(),
            max: z.number().optional(),
          })
          .optional(),
        familySituations: z.array(z.string()).optional(),
        genders: z.array(z.string()).optional(),
        otherCharacteristics: z.array(z.string()).optional(),
      })
      .optional(),
    updatedAt: z
      .object({
        on: z.string().optional(),
        before: z.string().optional(),
        after: z.string().optional(),
      })
      .optional(),
    pagination: z
      .object({
        page: z.number().optional(),
        limit: z.number().optional(),
      })
      .optional(),
  })
  .describe(
    'Exhaustive request body schema for POST /new-search/:lang? (non-admin route).',
  );
export type V20260303SearchRequest = z.infer<
  typeof v20260303SearchRequestSchema
>;
export type v20260303SearchRequestSchemaType = z.infer<
  typeof v20260303SearchRequestSchema
>;

export default v20260303SearchRequestSchema;
