export const OPENAPI_OPERATION_TARGET = Symbol('OPENAPI_OPERATION_TARGET');
export const OPENAPI_DECORATED_MODULE = Symbol('OPENAPI_DECORATED_MODULE');
export const ARTIFACTS_OUTPUT_DIRECTORY = Symbol('ARTIFACTS_OUTPUT_DIRECTORY');
