import { promises as fs } from 'fs';
import * as path from 'path';
import { Inject, Injectable, Optional } from '@nestjs/common';
import type { Type } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { z } from 'zod';

import { ChangelogGenerator } from './changelog/changelog.generator';
import { ContractOpenApiGenerator } from './openapi/contract-openapi.generator';
import {
  VersionedSchemaGenerator,
  type FirstVersionSeedSource,
  type GenerateVersionedSchemasResult,
  type SchemaKind,
} from './schema/versioned-schema.generator';
import { VersionRegistry } from '../versioning/version-registry';
import {
  ARTIFACTS_OUTPUT_DIRECTORY,
  FIRST_VERSION_SCHEMA_SEED_CONFIG,
  OPENAPI_DECORATED_MODULE,
  OPENAPI_OPERATION_TARGET,
  type FirstVersionSchemaSeedConfig,
} from './artifact-generation.tokens';
import type {
  ApiVersion,
  CompiledVersion,
  OpenApiOperationTarget,
  ValidationSchemaCache,
} from '../versioning/versioning.types';
import {
  REQUEST_SCHEMAS_BY_VERSION,
  RESPONSE_SCHEMAS_BY_VERSION,
} from '../runtime/versioning.tokens';

const GENERATED_TS_HEADER = [
  '/**',
  ' * DO NOT EDIT: This file is generated by search-api artifact generation.',
  ' */',
  '',
].join('\n');

const GENERATED_MD_HEADER =
  '<!-- DO NOT EDIT: This file is generated by search-api artifact generation. -->\n\n';

const GENERATED_OPENAPI_METADATA_NOTE =
  'DO NOT EDIT: This file is generated by search-api artifact generation.';

@Injectable()
export class ArtifactGenerationService {
  private readonly versionedSchemaGenerator = new VersionedSchemaGenerator();
  private readonly contractOpenApiGenerator = new ContractOpenApiGenerator();
  private readonly changelogGenerator = new ChangelogGenerator();

  constructor(
    private readonly registry: VersionRegistry,
    @Inject(OPENAPI_DECORATED_MODULE)
    private readonly openApiDecoratedModule: Type<unknown>,
    @Inject(OPENAPI_OPERATION_TARGET)
    private readonly openApiOperationTarget: OpenApiOperationTarget,
    @Inject(ARTIFACTS_OUTPUT_DIRECTORY)
    private readonly outputDirectory: string,
    @Optional()
    @Inject(FIRST_VERSION_SCHEMA_SEED_CONFIG)
    private readonly firstVersionSchemaSeedConfig?: FirstVersionSchemaSeedConfig,
    @Optional()
    @Inject(REQUEST_SCHEMAS_BY_VERSION)
    private readonly requestSchemasByVersion?: ValidationSchemaCache,
    @Optional()
    @Inject(RESPONSE_SCHEMAS_BY_VERSION)
    private readonly responseSchemasByVersion?: ValidationSchemaCache,
  ) {}

  async generateArtifacts(): Promise<void> {
    await fs.mkdir(this.outputDirectory, { recursive: true });
    const [requestFirstVersionSeed, responseFirstVersionSeed] =
      await Promise.all([
        this.resolveFirstVersionSeedSource('request'),
        this.resolveFirstVersionSeedSource('response'),
      ]);

    const sharedInput = {
      supportedVersions: this.registry.supportedVersions,
      compiledVersions: this.registry.compiledVersions,
      toSchemaConstName: (version: ApiVersion, kind: 'request' | 'response') =>
        this.toSchemaConstName(version, kind),
      schemaFilePathForVersion: (version: ApiVersion, kind: SchemaKind) =>
        this.schemaFilePathForVersion(version, kind),
    };

    const [requestResult, responseResult] = await Promise.all([
      this.versionedSchemaGenerator.generateVersionedSchemas({
        ...sharedInput,
        kind: 'request',
        firstVersionSeed: requestFirstVersionSeed,
      }),
      this.versionedSchemaGenerator.generateVersionedSchemas({
        ...sharedInput,
        kind: 'response',
        firstVersionSeed: responseFirstVersionSeed,
      }),
    ]);

    this.assertMatchingCreatedVersions(requestResult, responseResult);

    await fs.writeFile(
      this.contractsManifestPath(),
      this.buildContractsManifest(this.registry.supportedVersions),
      'utf8',
    );

    const versionsToGenerate = this.registry.supportedVersions;

    const baseOpenApiDocument = await this.buildBaseOpenApiDocument();
    const compiledByVersion = new Map<ApiVersion, CompiledVersion>(
      this.registry.compiledVersions.map((version) => [
        version.version,
        version,
      ]),
    );
    const firstVersion = this.registry.supportedVersions[0];

    for (const version of versionsToGenerate) {
      const compiledVersion = compiledByVersion.get(version);
      if (!compiledVersion) {
        throw new Error(
          `Missing compiled version payload for ${version} while generating artifacts.`,
        );
      }

      const requestSchema = this.resolveSchemaForVersion(
        'request',
        version,
        firstVersion,
        requestResult.schemasByVersion,
      );
      const responseSchema = this.resolveSchemaForVersion(
        'response',
        version,
        firstVersion,
        responseResult.schemasByVersion,
      );
      if (!requestSchema || !responseSchema) {
        throw new Error(
          `Missing in-memory schema outputs for version ${version}.`,
        );
      }

      const openApiDocument =
        this.contractOpenApiGenerator.buildVersionOpenApiDocument({
          version,
          baseOpenApiDocument,
          openApiOperationTarget: this.openApiOperationTarget,
          requestSchema,
          responseSchema,
        });
      const openApiFilePath = this.openApiFilePath(version);
      const changelogFilePath = this.changelogFilePath(version);
      await fs.mkdir(path.dirname(openApiFilePath), { recursive: true });

      await fs.writeFile(
        openApiFilePath,
        `${JSON.stringify(
          this.withGeneratedOpenApiMetadata(openApiDocument),
          null,
          2,
        )}\n`,
        'utf8',
      );

      await fs.writeFile(
        changelogFilePath,
        this.withGeneratedMdHeader(
          this.changelogGenerator.buildVersionChangelog(compiledVersion),
        ),
        'utf8',
      );
    }
  }

  private async buildBaseOpenApiDocument(): Promise<Record<string, unknown>> {
    const app = await NestFactory.create(this.openApiDecoratedModule, {
      logger: false,
    });

    try {
      const config = new DocumentBuilder()
        .setTitle('Soliguide Search API')
        .setDescription(
          'Static operation metadata from decorators with versioned payload schemas.',
        )
        .setVersion(this.registry.canonicalVersion)
        .build();

      return SwaggerModule.createDocument(app, config) as unknown as Record<
        string,
        unknown
      >;
    } finally {
      await app.close();
    }
  }

  private toSchemaConstName(
    version: ApiVersion,
    kind: 'request' | 'response',
  ): string {
    const normalizedVersion = version.replace(/-/g, '');
    const firstVersion = this.registry.supportedVersions[0];
    const seedExportName =
      kind === 'request'
        ? this.firstVersionSchemaSeedConfig?.request.exportName
        : this.firstVersionSchemaSeedConfig?.response.exportName;

    if (firstVersion && seedExportName) {
      const firstNormalizedVersion = firstVersion.replace(/-/g, '');
      const prefix = `v${firstNormalizedVersion}`;
      if (seedExportName.startsWith(prefix)) {
        return `v${normalizedVersion}${seedExportName.slice(prefix.length)}`;
      }
    }

    return `v${normalizedVersion}${kind === 'request' ? 'Request' : 'Response'}Schema`;
  }

  private buildContractsManifest(versions: readonly ApiVersion[]): string {
    const importLines: string[] = [
      GENERATED_TS_HEADER.trimEnd(),
      "import { z } from 'zod';",
    ];

    for (const version of versions) {
      importLines.push(
        `import { ${this.toSchemaConstName(version, 'request')} } from '${this.schemaModuleImportPath(version, 'request')}';`,
      );
      importLines.push(
        `import { ${this.toSchemaConstName(version, 'response')} } from '${this.schemaModuleImportPath(version, 'response')}';`,
      );
    }

    const requestEntries = versions
      .map(
        (version) =>
          `  ['${version}', ${this.toSchemaConstName(version, 'request')}] as [ApiVersion, z.ZodTypeAny],`,
      )
      .join('\n');
    const responseEntries = versions
      .map(
        (version) =>
          `  ['${version}', ${this.toSchemaConstName(version, 'response')}] as [ApiVersion, z.ZodTypeAny],`,
      )
      .join('\n');

    return [
      ...importLines,
      '',
      'type ApiVersion = `${number}-${number}-${number}`;',
      '',
      'export const requestSchemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny> = new Map<ApiVersion, z.ZodTypeAny>(',
      '[',
      requestEntries,
      ']);',
      '',
      'export const responseSchemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny> = new Map<ApiVersion, z.ZodTypeAny>(',
      '[',
      responseEntries,
      ']);',
      '',
    ].join('\n');
  }

  private async resolveFirstVersionSeedSource(
    kind: SchemaKind,
  ): Promise<FirstVersionSeedSource> {
    const firstVersion = this.registry.supportedVersions[0];
    if (!firstVersion) {
      throw new Error('No supported API versions configured.');
    }

    const seedConfig = this.firstVersionSchemaSeedConfig?.[kind];
    if (!seedConfig) {
      throw new Error(
        `Missing first-version ${kind} seed configuration. Provide ${String(FIRST_VERSION_SCHEMA_SEED_CONFIG)} in SearchModule.`,
      );
    }

    const generatedFilePath = this.schemaFilePathForVersion(firstVersion, kind);
    const sourceFilePath = await this.resolveSeedSourceFilePath(
      generatedFilePath,
      seedConfig.importPath,
    );

    return {
      sourceFilePath,
      exportName: seedConfig.exportName,
    };
  }

  private async resolveSeedSourceFilePath(
    generatedFilePath: string,
    importPath: string,
  ): Promise<string> {
    if (!importPath.startsWith('.')) {
      throw new Error(
        `First-version schema seed import "${importPath}" must be a relative path.`,
      );
    }

    const fromDirectory = path.dirname(generatedFilePath);
    const candidateWithoutExtension = path.resolve(fromDirectory, importPath);
    const candidates = candidateWithoutExtension.endsWith('.ts')
      ? [candidateWithoutExtension]
      : [
          `${candidateWithoutExtension}.ts`,
          path.join(candidateWithoutExtension, 'index.ts'),
        ];

    for (const candidate of candidates) {
      try {
        await fs.access(candidate);
        return candidate;
      } catch {
        // Keep trying.
      }
    }

    throw new Error(
      `Could not resolve first-version schema seed source "${importPath}" from "${fromDirectory}".`,
    );
  }

  private contractsManifestPath(): string {
    return path.join(this.outputDirectory, 'contracts.generated.ts');
  }

  private schemaFilePathForVersion(
    version: ApiVersion,
    kind: SchemaKind,
  ): string {
    return path.join(
      this.outputDirectory,
      version,
      `${this.registry.definition.resource}.${kind}`,
      `${version}.${this.registry.definition.resource}.${kind}.generated.ts`,
    );
  }

  private schemaModuleImportPath(
    version: ApiVersion,
    kind: SchemaKind,
  ): string {
    return `./${version}/${this.registry.definition.resource}.${kind}/${version}.${this.registry.definition.resource}.${kind}.generated`;
  }

  private openApiFilePath(version: ApiVersion): string {
    return path.join(
      this.outputDirectory,
      version,
      `${version}.openapi.generated.json`,
    );
  }

  private changelogFilePath(version: ApiVersion): string {
    return path.join(
      this.outputDirectory,
      version,
      `${version}.changelog.generated.md`,
    );
  }

  private withGeneratedOpenApiMetadata(
    document: Record<string, unknown>,
  ): Record<string, unknown> {
    return {
      'x-generated-file-warning': GENERATED_OPENAPI_METADATA_NOTE,
      ...document,
    };
  }

  private withGeneratedMdHeader(content: string): string {
    return `${GENERATED_MD_HEADER}${content}`;
  }

  private resolveSchemaForVersion(
    kind: 'request' | 'response',
    version: ApiVersion,
    firstVersion: ApiVersion | undefined,
    generatedSchemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny>,
  ): z.ZodTypeAny | undefined {
    const generatedSchema = generatedSchemasByVersion.get(version);
    if (generatedSchema) {
      return generatedSchema;
    }

    const existingSchema = (
      kind === 'request'
        ? this.requestSchemasByVersion
        : this.responseSchemasByVersion
    )?.get(version);
    if (existingSchema) {
      return existingSchema;
    }

    if (version === firstVersion) {
      return kind === 'request'
        ? this.registry.definition.baseRequestSchema
        : this.registry.definition.baseResponseSchema;
    }

    return undefined;
  }

  private assertMatchingCreatedVersions(
    requestResult: GenerateVersionedSchemasResult,
    responseResult: GenerateVersionedSchemasResult,
  ): readonly ApiVersion[] {
    const requestVersions = requestResult.createdVersions;
    const responseVersions = responseResult.createdVersions;
    if (requestVersions.length !== responseVersions.length) {
      throw new Error(
        'Request and response schema generation produced different created version counts.',
      );
    }

    for (let index = 0; index < requestVersions.length; index += 1) {
      if (requestVersions[index] !== responseVersions[index]) {
        throw new Error(
          `Request and response schema generation disagree on created version at index ${index}.`,
        );
      }
    }

    return requestVersions;
  }
}
