# Soliguide: Useful information for those who need it
#
# SPDX-FileCopyrightText: © 2024 Solinum
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: "Signaler un bug"
description: "Problème à corriger / anomalie bloquante pour les utilisateurs"
title: "🐞 Bug - "
labels: ["bug"]
type: "Bug"
projects: ["solinumasso/2"]
body:
  - type: checkboxes
    id: sites
    attributes:
      label: "🖥️ Produit(s) concerné(s)"
      options:
        - label: "Application mobile"
          required: false
        - label: "Backoffice"
          required: false
        - label: "Soliguide.fr"
          required: false
        - label: "Soliguia"
          required: false
        - label: "Intégration de donnée"
          required: false
        - label: "Dashboards"
          required: false
        - label: "API Soliguide"
          required: false
        - label: "Design system"
          required: false
  - type: textarea
    id: description
    attributes:
      label: "🚫 Description du problème: comment as-t-il été trouvé ?"
      description: "Précisez les étapes pour reproduire directement. \nVous pouvez glisser des captures d'écran directement dans ce champs. \n🧨 **IMPORTANT** : Veillez à masquer toute information personnelle ou confidentielle 🧨 "
      placeholder: "Ex: L'utilisateur n'arrive pas à consulter une fiche ou réaliser une recherche, le mail de renouvellement de mot de passe n'arrive jamais, etc"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "🔮 Comportement attendu"
      placeholder: "Décrivez ce qui devrait se passer normalement"
    validations:
      required: true
