/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  CountryCodes,
  GeoTypes,
  PLACE_LANGUAGES_LIST_MAP_KEY,
  PlaceType,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  UpdatedAtInterval,
  WelcomedPublics,
  WIDGETS_AVAILABLE,
} from "@soliguide/common";
import { z } from "zod";

const categoriesEnumSchema = z
  .enum(Categories)
  .meta({ id: "Common_Categories" });
const placeLanguagesEnumSchema = z
  .enum(PLACE_LANGUAGES_LIST_MAP_KEY)
  .describe("Language code spoken at the place.")
  .meta({ id: "Common_PlaceLanguages" });
const countryCodesEnumSchema = z
  .enum([CountryCodes.FR, CountryCodes.ES, CountryCodes.AD])
  .describe(
    "Country code restricted to Soliguide countries. Format ISO 3166-1 alpha-2."
  )
  .meta({ id: "Common_SoliguideCountries" });
const placeTypeEnumSchema = z.enum(PlaceType).meta({ id: "Common_PlaceType" });
const publicsAdministrativeEnumSchema = z
  .enum(PublicsAdministrative)
  .meta({ id: "Common_PublicsAdministrative" });
const publicsFamilyEnumSchema = z
  .enum(PublicsFamily)
  .meta({ id: "Common_PublicsFamily" });
const publicsGenderEnumSchema = z
  .enum(PublicsGender)
  .meta({ id: "Common_PublicsGender" });
const publicsOtherEnumSchema = z
  .enum(PublicsOther)
  .meta({ id: "Common_PublicsOther" });
const updatedAtIntervalEnumSchema = z
  .enum(UpdatedAtInterval)
  .meta({ id: "Common_UpdatedAtInterval" });
const welcomedPublicsEnumSchema = z
  .enum(WelcomedPublics)
  .meta({ id: "Common_WelcomedPublics" });

const locationSharedFields = {
  distance: z.coerce
    .number()
    .nullable()
    .optional()
    .describe("Search radius in kilometers for position-based search.")
    .meta({ example: 5 }),
  label: z
    .string()
    .nullable()
    .optional()
    .describe("Free-text label associated with the searched geographic area."),
  department: z
    .string()
    .nullable()
    .optional()
    .describe("Department name of the searched area."),
  regionCode: z
    .string()
    .nullable()
    .optional()
    .describe("Administrative code of the searched region."),
  departmentCode: z
    .string()
    .nullable()
    .optional()
    .describe(
      "Department code of the searched area. Examples: `974`, `2A`, `91`, `06`."
    ),
  region: z
    .string()
    .nullable()
    .optional()
    .describe("Region name of the searched area."),
  country: countryCodesEnumSchema
    .nullable()
    .optional()
    .describe(
      "Country code. Restricted to Soliguide countries for non-API users."
    ),
};

const locationSchema = z
  .discriminatedUnion("geoType", [
    z.looseObject({
      geoType: z.literal(GeoTypes.POSITION),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        )
        .meta({ example: [2.3522, 48.8566] }),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.UNKNOWN),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.BOROUGH),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for a borough search. This value usually includes the postal code."
        )
        .meta({ example: "75013" }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITY),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for a city search. This value can include the postal code suffix used by Soliguide."
        )
        .meta({ example: "paris-75013" }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.COUNTRY),
      geoValue: z
        .enum([CountryCodes.FR, CountryCodes.ES, CountryCodes.AD])
        .describe(
          "Country code searched when `geoType` is `country`. Restricted to Soliguide countries. Format ISO 3166-1 alpha-2."
        )
        .meta({ example: CountryCodes.FR }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.DEPARTMENT),
      geoValue: z
        .string()
        .min(1)
        .describe("Geographic identifier for a department search.")
        .meta({ example: "75" }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.REGION),
      geoValue: z
        .string()
        .min(1)
        .describe("Geographic identifier for a region search.")
        .meta({ example: "ile-de-france" }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITIES_GROUP),
      geoValue: z
        .string()
        .min(1)
        .describe("Free-text search value used to target a group of cities.")
        .meta({ example: "paris" }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Geographic coordinates used when `geoType` is `position`, as `[longitude, latitude]`. Format GeoJSON."
        ),
      ...locationSharedFields,
    }),
  ])
  .describe("Geographic mode used by the search location.")
  .meta({ id: "SearchRequest_Location" });

const modalitiesSchema = z
  .looseObject({
    animal: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places accepting animals."),
    appointment: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places requiring an appointment."),
    inconditionnel: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Filter on places with unconditional access. When `true`, it targets places where unconditional access is the applicable access mode."
      ),
    inscription: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places requiring prior registration."),
    orientation: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places requiring orientation."),
    pmr: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places accessible to people with reduced mobility."),
    price: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on fee-based places or services."),
    sign: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Filter on places offering sign-language accessibility."),
  })
  .catchall(z.unknown())
  .describe("Access condition filters.")
  .meta({ id: "SearchRequest_Modalities" });

const publicsSchema = z
  .looseObject({
    accueil: welcomedPublicsEnumSchema
      .nullable()
      .optional()
      .describe(
        "Type of welcome expected for the public: unconditional, preferential or exclusive."
      ),
    age: z
      .object({
        min: z.coerce
          .number()
          .int()
          .min(0)
          .max(99)
          .nullable()
          .optional()
          .describe(
            "Minimum age used by the audience filter. Values from `0` to `99` are accepted."
          ),
        max: z.coerce
          .number()
          .int()
          .min(0)
          .max(99)
          .nullable()
          .optional()
          .describe(
            "Maximum age used by the audience filter. Values from `0` to `99` are accepted."
          ),
      })
      .nullable()
      .optional()
      .describe("Age filter for the welcomed public."),
    gender: z
      .array(publicsGenderEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Gender-related audience filters. If all possible values are selected, it is treated as no restriction."
      ),
    administrative: z
      .array(publicsAdministrativeEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Administrative-status audience filters. If all possible values are selected, it is treated as no restriction."
      ),
    familialle: z
      .array(publicsFamilyEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Family-situation audience filters. If all possible values are selected, it is treated as no restriction."
      ),
    other: z
      .array(publicsOtherEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Other audience filters. If all possible values are selected, it is treated as no restriction."
      ),
  })
  .describe("Public audience filters.")
  .meta({ id: "SearchRequest_Publics" });

const updatedAtSchema = z
  .looseObject({
    intervalType: updatedAtIntervalEnumSchema
      .nullable()
      .optional()
      .describe("Comparison mode used for the update-date filter."),
    value: z
      .string()
      .nullable()
      .optional()
      .describe("Date used by the update filter. Format ISO 8601.")
      .meta({ example: "2026-01-01T00:00:00.000Z" }),
  })
  .describe("Filter places by update date.")
  .meta({ id: "SearchRequest_UpdatedAt" });

const optionsSchema = z
  .looseObject({
    sortBy: z
      .enum([
        "createdAt",
        "lieu_id",
        "name",
        "distance",
        "slugs.infos.name",
        "status",
        "updatedAt",
      ])
      .nullable()
      .optional()
      .describe("Field used to sort the search results."),
    sortValue: z.coerce
      .number()
      .refine((value) => value === 1 || value === -1)
      .nullable()
      .optional()
      .describe("Sorting direction: `1` ascending, `-1` descending.")
      .meta({ example: 1 }),
    page: z.coerce
      .number()
      .int()
      .nullable()
      .optional()
      .describe("Page number of the paginated results.")
      .meta({ example: 1 }),
    limit: z.coerce
      .number()
      .int()
      .nullable()
      .optional()
      .describe("Maximum number of results returned per page.")
      .meta({ example: 10 }),
    fields: z
      .string()
      .min(1)
      .nullable()
      .optional()
      .describe(
        "Space-separated list of fields to include in the response payload."
      ),
  })
  .describe("Pagination, sorting and field-selection options.")
  .meta({ id: "SearchRequest_Options" });

export const v20260101SearchRequestSchema = z
  .looseObject({
    location: locationSchema.describe(
      "Primary location constraint (required by route validation)."
    ),
    locations: z
      .array(locationSchema)
      .nullable()
      .optional()
      .describe(
        "Optional list of locations for widget-like multi-location search."
      ),
    category: categoriesEnumSchema
      .nullable()
      .optional()
      .describe("Single service category filter."),
    categories: z
      .array(categoriesEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Multiple categories (restricted by user status at route level)."
      ),
    placeType: placeTypeEnumSchema
      .default(PlaceType.PLACE)
      .describe("Resource type to search: fixed places or itineraries.")
      .meta({ example: PlaceType.PLACE }),
    word: z
      .string()
      .nullable()
      .optional()
      .describe("Free-text search applied to place and service content."),
    openToday: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Only return results that are open today.")
      .meta({
        example: true,
      }),
    modalities: modalitiesSchema.nullable().optional(),
    publics: publicsSchema.nullable().optional(),
    languages: z
      .array(placeLanguagesEnumSchema)
      .nullable()
      .optional()
      .describe("Filter places by languages spoken at the place.")
      .meta({ example: ["fr"] }),
    widgetId: z
      .string()
      .refine(
        (value) =>
          WIDGETS_AVAILABLE.includes(
            value as (typeof WIDGETS_AVAILABLE)[number]
          ),
        {
          message: "widgetId must be one of WIDGETS_AVAILABLE",
        }
      )
      .nullable()
      .optional()
      .describe(
        "Widget identifier used to apply widget-specific search rules."
      ),
    updatedAt: updatedAtSchema
      .nullable()
      .optional()
      .describe("Update-date filter."),
    options: optionsSchema
      .nullable()
      .optional()
      .describe("Search result options."),
  })
  .describe(
    "Exhaustive request body schema for POST /new-search/:lang? (non-admin route)."
  )
  .meta({ id: "v20260101SearchRequest" });
export type V20260101SearchRequest = z.infer<
  typeof v20260101SearchRequestSchema
>;

export default v20260101SearchRequestSchema;
