/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  CountryCodes,
  GeoTypes,
  PLACE_LANGUAGES_LIST_MAP_KEY,
  PlaceType,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  UpdatedAtInterval,
  WelcomedPublics,
  WIDGETS_AVAILABLE,
} from "@soliguide/common";
import { z } from "zod";

const placeLanguagesEnumSchema = z
  .enum(PLACE_LANGUAGES_LIST_MAP_KEY)
  .describe("Language code spoken at the place.")
  .meta({ id: "Common_PlaceLanguages" });

const locationSharedFields = {
  distance: z.coerce
    .number()
    .nullable()
    .optional()
    .describe("Search radius in kilometers for position-based search."),
  label: z.string().nullable().optional(),
  department: z.string().nullable().optional(),
  regionCode: z.string().nullable().optional(),
  departmentCode: z.string().nullable().optional(),
  region: z.string().nullable().optional(),
  country: z
    .enum(CountryCodes)
    .nullable()
    .optional()
    .describe(
      "Country code. Restricted to Soliguide countries for non-API users."
    ),
};

const locationSchema = z
  .discriminatedUnion("geoType", [
    z.looseObject({
      geoType: z.literal(GeoTypes.POSITION),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.UNKNOWN),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.BOROUGH),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITY),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.COUNTRY),
      geoValue: z
        .enum([CountryCodes.FR, CountryCodes.ES, CountryCodes.AD])
        .describe(
          "Country code searched when `geoType` is `country`. Restricted to Soliguide countries. Format ISO 3166-1 alpha-2."
        )
        .meta({ example: CountryCodes.FR }),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.DEPARTMENT),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.REGION),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITIES_GROUP),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
  ])
  .describe("Geographic mode used by the search location.");

const modalitiesSchema = z
  .looseObject({
    animal: z.coerce.boolean().nullable().optional(),
    appointment: z.coerce.boolean().nullable().optional(),
    inconditionnel: z.coerce.boolean().nullable().optional(),
    inscription: z.coerce.boolean().nullable().optional(),
    orientation: z.coerce.boolean().nullable().optional(),
    pmr: z.coerce.boolean().nullable().optional(),
    price: z.coerce.boolean().nullable().optional(),
    sign: z.coerce.boolean().nullable().optional(),
  })
  .catchall(z.unknown());

const publicsSchema = z
  .looseObject({
    accueil: z.enum(WelcomedPublics).nullable().optional(),
    age: z
      .object({
        min: z.coerce.number().int().min(0).max(99).nullable().optional(),
        max: z.coerce.number().int().min(0).max(99).nullable().optional(),
      })
      .nullable()
      .optional(),
    gender: z.array(z.enum(PublicsGender)).nullable().optional(),
    administrative: z
      .array(z.enum(PublicsAdministrative))
      .nullable()
      .optional(),
    familialle: z.array(z.enum(PublicsFamily)).nullable().optional(),
    other: z.array(z.enum(PublicsOther)).nullable().optional(),
  })
  .describe("Public audience filters.");

const updatedAtSchema = z.looseObject({
  intervalType: z.enum(UpdatedAtInterval).nullable().optional(),
  value: z.coerce.date().nullable().optional(),
});

const optionsSchema = z.looseObject({
  sortBy: z
    .enum([
      "createdAt",
      "lieu_id",
      "name",
      "distance",
      "slugs.infos.name",
      "status",
      "updatedAt",
    ])
    .nullable()
    .optional(),
  sortValue: z.coerce
    .number()
    .refine((value) => value === 1 || value === -1)
    .nullable()
    .optional(),
  page: z.coerce.number().int().nullable().optional(),
  limit: z.coerce.number().int().nullable().optional(),
  fields: z.string().min(1).nullable().optional(),
});
export const v20260101SearchRequestSchema = z
  .looseObject({
    location: locationSchema.describe(
      "Primary location constraint (required by route validation)."
    ),
    locations: z
      .array(locationSchema)
      .nullable()
      .optional()
      .describe(
        "Optional list of locations for widget-like multi-location search."
      ),
    category: z.enum(Categories).nullable().optional(),
    categories: z
      .array(z.enum(Categories))
      .nullable()
      .optional()
      .describe(
        "Multiple categories (restricted by user status at route level)."
      ),
    placeType: z
      .enum(PlaceType)
      .default(PlaceType.PLACE)
      .describe("Resource type to search: fixed places or itineraries."),
    word: z.string().nullable().optional(),
    openToday: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Only return results that are open today.")
      .meta({
        example: true,
      }),
    modalities: modalitiesSchema.nullable().optional(),
    publics: publicsSchema.nullable().optional(),
    languages: z
      .array(placeLanguagesEnumSchema)
      .nullable()
      .optional()
      .describe("Filter places by languages spoken at the place.")
      .meta({ example: ["fr"] }),
    widgetId: z
      .string()
      .refine(
        (value) =>
          WIDGETS_AVAILABLE.includes(
            value as (typeof WIDGETS_AVAILABLE)[number]
          ),
        {
          message: "widgetId must be one of WIDGETS_AVAILABLE",
        }
      )
      .nullable()
      .optional(),
    updatedAt: updatedAtSchema.nullable().optional(),
    options: optionsSchema.nullable().optional(),
  })
  .describe(
    "Exhaustive request body schema for POST /new-search/:lang? (non-admin route)."
  );
export type V20260101SearchRequest = z.infer<
  typeof v20260101SearchRequestSchema
>;

export default v20260101SearchRequestSchema;
