/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  CountryCodes,
  GeoTypes,
  PLACE_LANGUAGES_LIST_MAP_KEY,
  PlaceType,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  UpdatedAtInterval,
  WelcomedPublics,
  WIDGETS_AVAILABLE,
} from "@soliguide/common";
import { z } from "zod";

const categoriesEnumSchema = z
  .enum(Categories)
  .meta({ id: "Common_Categories" });
const countryCodesEnumSchema = z
  .enum(CountryCodes)
  .meta({ id: "Common_CountryCodes" });
const placeTypeEnumSchema = z.enum(PlaceType).meta({ id: "Common_PlaceType" });
const publicsAdministrativeEnumSchema = z
  .enum(PublicsAdministrative)
  .meta({ id: "Common_PublicsAdministrative" });
const publicsFamilyEnumSchema = z
  .enum(PublicsFamily)
  .meta({ id: "Common_PublicsFamily" });
const publicsGenderEnumSchema = z
  .enum(PublicsGender)
  .meta({ id: "Common_PublicsGender" });
const publicsOtherEnumSchema = z
  .enum(PublicsOther)
  .meta({ id: "Common_PublicsOther" });
const updatedAtIntervalEnumSchema = z
  .enum(UpdatedAtInterval)
  .meta({ id: "Common_UpdatedAtInterval" });
const welcomedPublicsEnumSchema = z
  .enum(WelcomedPublics)
  .meta({ id: "Common_WelcomedPublics" });

const locationSharedFields = {
  distance: z.coerce
    .number()
    .nullable()
    .optional()
    .describe("Search radius in kilometers for position-based search."),
  label: z.string().nullable().optional(),
  department: z.string().nullable().optional(),
  regionCode: z.string().nullable().optional(),
  departmentCode: z.string().nullable().optional(),
  region: z.string().nullable().optional(),
  country: countryCodesEnumSchema
    .nullable()
    .optional()
    .describe(
      "Country code. Restricted to Soliguide countries for non-API users."
    ),
};

const locationSchema = z
  .discriminatedUnion("geoType", [
    z.looseObject({
      geoType: z.literal(GeoTypes.POSITION),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.UNKNOWN),
      geoValue: z
        .string()
        .nullable()
        .optional()
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.BOROUGH),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITY),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.COUNTRY),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.DEPARTMENT),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.REGION),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
    z.looseObject({
      geoType: z.literal(GeoTypes.CITIES_GROUP),
      geoValue: z
        .string()
        .min(1)
        .describe(
          "Geographic identifier for non-position searches (country, region, department, city, etc.)."
        ),
      coordinates: z
        .array(z.coerce.number())
        .length(2)
        .nullable()
        .optional()
        .describe(
          "Longitude/latitude coordinates used when geoType is position."
        ),
      ...locationSharedFields,
    }),
  ])
  .describe("Geographic mode used by the search location.")
  .meta({ id: "SearchRequest_Location" });

const modalitiesSchema = z
  .looseObject({
    animal: z.coerce.boolean().nullable().optional(),
    appointment: z.coerce.boolean().nullable().optional(),
    inconditionnel: z.coerce.boolean().nullable().optional(),
    inscription: z.coerce.boolean().nullable().optional(),
    orientation: z.coerce.boolean().nullable().optional(),
    pmr: z.coerce.boolean().nullable().optional(),
    price: z.coerce.boolean().nullable().optional(),
    sign: z.coerce.boolean().nullable().optional(),
  })
  .catchall(z.unknown())
  .meta({ id: "SearchRequest_Modalities" });

const publicsSchema = z
  .looseObject({
    accueil: welcomedPublicsEnumSchema.nullable().optional(),
    age: z
      .object({
        min: z.coerce.number().int().min(0).max(99).nullable().optional(),
        max: z.coerce.number().int().min(0).max(99).nullable().optional(),
      })
      .nullable()
      .optional(),
    gender: z.array(publicsGenderEnumSchema).nullable().optional(),
    administrative: z
      .array(publicsAdministrativeEnumSchema)
      .nullable()
      .optional(),
    familialle: z.array(publicsFamilyEnumSchema).nullable().optional(),
    other: z.array(publicsOtherEnumSchema).nullable().optional(),
  })
  .describe("Public audience filters.")
  .meta({ id: "SearchRequest_Publics" });

const updatedAtSchema = z
  .looseObject({
    intervalType: updatedAtIntervalEnumSchema.nullable().optional(),
    value: z.coerce.date().nullable().optional(),
  })
  .meta({ id: "SearchRequest_UpdatedAt" });

const optionsSchema = z
  .looseObject({
    sortBy: z
      .enum([
        "createdAt",
        "lieu_id",
        "name",
        "distance",
        "slugs.infos.name",
        "status",
        "updatedAt",
      ])
      .nullable()
      .optional(),
    sortValue: z.coerce
      .number()
      .refine((value) => value === 1 || value === -1)
      .nullable()
      .optional(),
    page: z.coerce.number().int().nullable().optional(),
    limit: z.coerce.number().int().nullable().optional(),
    fields: z.string().min(1).nullable().optional(),
  })
  .meta({ id: "SearchRequest_Options" });

export const v20260101SearchRequestSchema = z
  .looseObject({
    location: locationSchema.describe(
      "Primary location constraint (required by route validation)."
    ),
    locations: z
      .array(locationSchema)
      .nullable()
      .optional()
      .describe(
        "Optional list of locations for widget-like multi-location search."
      ),
    category: categoriesEnumSchema.nullable().optional(),
    categories: z
      .array(categoriesEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Multiple categories (restricted by user status at route level)."
      ),
    placeType: placeTypeEnumSchema
      .default(PlaceType.PLACE)
      .describe("Resource type to search: fixed places or itineraries."),
    word: z.string().nullable().optional(),
    openToday: z.coerce
      .boolean()
      .nullable()
      .optional()
      .describe("Only return results that are open today.")
      .meta({
        example: true,
      }),
    modalities: modalitiesSchema.nullable().optional(),
    publics: publicsSchema.nullable().optional(),
    languages: z
      .string()
      .refine((value) => PLACE_LANGUAGES_LIST_MAP_KEY.includes(value), {
        message: "languages must be one of PLACE_LANGUAGES_LIST_MAP_KEY",
      })
      .nullable()
      .optional(),
    widgetId: z
      .string()
      .refine(
        (value) =>
          WIDGETS_AVAILABLE.includes(
            value as (typeof WIDGETS_AVAILABLE)[number]
          ),
        {
          message: "widgetId must be one of WIDGETS_AVAILABLE",
        }
      )
      .nullable()
      .optional(),
    updatedAt: updatedAtSchema.nullable().optional(),
    options: optionsSchema.nullable().optional(),
  })
  .describe(
    "Exhaustive request body schema for POST /new-search/:lang? (non-admin route)."
  )
  .meta({ id: "v20260101SearchRequest" });
export type V20260101SearchRequest = z.infer<
  typeof v20260101SearchRequestSchema
>;

export default v20260101SearchRequestSchema;
