/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import { z } from "zod";

import { v20260101SearchPlaceResponseSchema } from "./2026-01-01.search-response.schema.generated";

export const v20260101PlaceResponseSchema =
  v20260101SearchPlaceResponseSchema;

export type V20260101PlaceResponse = z.infer<
  typeof v20260101PlaceResponseSchema
>;

export default v20260101PlaceResponseSchema;
