export const SPANISH_ABBREVIATIONS = {
  "punto kilométrico": ["p. k."],
  arroyo: ["arr."],
  avenida: ["av.", "avd.", "avda.", "(av.a)"],
  barrio: ["Bo.", "B.º"],
  bulevar: ["blvr."],
  calle: ["c.", "c/", "c\\", "cl."],
  callejón: ["call.n"],
  camino: ["c.º"],
  campillo: ["camp."],
  carrera: ["carr."],
  carretera: ["ctra.", "carret."],
  cerrillo: ["cerr."],
  costanilla: ["cost."],
  cuesta: ["cta."],
  ensanche: ["ens."],
  extrarradio: ["extr."],
  glorieta: ["gta.", "g.ta"],
  interior: ["int."],
  pasadizo: ["p.zo"],
  pasaje: ["p.je", "pje.", "ptge."],
  paseo: ["p.º", "pg."],
  plaza: ["p.za", "pza.", "pl.", "plza."],
  polígono: ["pol."],
  pradera: ["prad."],
  pretil: ["pret."],
  puente: ["p.te", "pte."],
  rambla: ["rbla."],
  ribera: ["rib."],
  ronda: ["r.da", "rda."],
  rotonda: ["rot."],
  travesía: ["tr."],
  vereda: ["ver.", "vda."],
};
