import { describe, it, expect, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";

describe("generate-caddy script", () => {
  it("generates redirections for historical slugs", async () => {
    const generatedFile = path.join(
      __dirname,
      "../../generated/category-redirects.caddy"
    );

    if (fs.existsSync(generatedFile)) {
      fs.unlinkSync(generatedFile);
    }

    await import("../generate-caddy");

    const content = fs.readFileSync(generatedFile, "utf-8");

    // Vérifie la structure du fichier généré
    expect(content).toContain("# AUTOGENERATED FILE — DO NOT EDIT");
    expect(content).toContain("map {http.request.orig_uri.path}");
    expect(content).toContain("@category_redirect_with_query");
    expect(content).toContain("@category_redirect_without_query");
    expect(content).toContain("redir {category_target_path}");

    // Vérifie que les anciennes catégories sont redirigées vers les nouvelles
    expect(content).toContain('~^(.*/search/.*)/(sante)(.*)$ "${2}" "${1}/health${3}"');
    expect(content).toContain('~^(.*/search/.*)/(depistage)(.*)$ "${2}" "${1}/std_testing${3}"');
  });
});
