// @index('./*', f => `export * from '${f.path}'`)
export * from "./campaignSource.dto";
export * from "./checkDuplicatesByAddressAndPlaceId.dto";
export * from "./checkDuplicatesByPlace.dto";
export * from "./date.dto";
export * from "./docUpload.dto";
export * from "./formatAddress.dto";
export * from "./forceChanges.dto";
export * from "./hours.dto";
export * from "./infos.dto";
export * from "./modalities.dto";
export * from "./parcours.dto";
export * from "./position.dto";
export * from "./publics.dto";
export * from "./services.dto";
export * from "./source.dto";
export * from "./status.dto";
export * from "./userContactDto";
export * from "./visibility.dto";
