export enum PlaceStatus {
  DRAFT = "DRAFT",
  ONLINE = "ONLINE",
  PERMANENTLY_CLOSED = "PERMANENTLY_CLOSED",
  OFFLINE = "OFFLINE",
}

export enum SearchPlaceStatus {
  DRAFT = "DRAFT",
  ONLINE = "ONLINE",
  PERMANENTLY_CLOSED = "PERMANENTLY_CLOSED",
  OFFLINE = "OFFLINE",
  ONE_MONTH_TO_OFFLINE = "ONE_MONTH_TO_OFFLINE",
}
