export enum TestAccounts {
  USER_ADMIN_SOLIGUIDE = "USER_ADMIN_SOLIGUIDE",
  USER_ADMIN_TERRITORY = "USER_ADMIN_TERRITORY",
  USER_API_ALIMENTATION = "USER_API_ALIMENTATION",
  USER_API_BLOCKED = "USER_API_BLOCKED",
  USER_API_DEFAULT = "USER_API_DEFAULT",
  USER_API_PARIS = "USER_API_PARIS",
  USER_PRO_EDITOR = "USER_PRO_EDITOR",
  USER_PRO_OWNER = "USER_PRO_OWNER",
  USER_PRO_OWNER_ORGA1_EDITOR_ORGA2 = "USER_PRO_OWNER_ORGA1_EDITOR_ORGA2",
  USER_PRO_READER = "USER_PRO_READER",
  USER_TRANSLATOR_EN_AR = "USER_TRANSLATOR_EN_AR",
}

export enum ExpectedStatus {
  FAIL = "fail",
  SUCCESS = "success",
  PROCESSING = "processing",
  NOT_FOUND = "not-found",
  ERROR = "error",
}

export type AuthTokens = { [_key in TestAccounts]: string | null };
