export enum UserStatus {
  SOLI_BOT = "SOLI_BOT",
  SIMPLE_USER = "SIMPLE_USER",
  API_USER = "API_USER",
  WIDGET_USER = "WIDGET_USER",
  VOLUNTEER = "VOLUNTEER",
  PRO = "PRO",
  ADMIN_TERRITORY = "ADMIN_TERRITORY",
  ADMIN_SOLIGUIDE = "ADMIN_SOLIGUIDE",
}
