/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  GeoTypes,
  PLACE_LANGUAGES_LIST_MAP_KEY,
  PlaceType,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  UpdatedAtInterval,
  WelcomedPublics,
  WIDGETS_AVAILABLE,
} from '@soliguide/common';
import { z } from 'zod';

const locationSchema = z
  .object({
    geoType: z
      .enum(GeoTypes)
      .describe('Geographic mode used by the search location.'),
    geoValue: z
      .string()
      .optional()
      .describe(
        'Geographic identifier for non-position searches (country, region, department, city, etc.).',
      ),
    coordinates: z
      .array(z.coerce.number())
      .length(2)
      .optional()
      .describe(
        'Longitude/latitude coordinates used when geoType is position.',
      ),
    distance: z.coerce
      .number()
      .optional()
      .describe('Search radius in kilometers for position-based search.'),
    label: z.string().optional(),
    department: z.string().optional(),
    regionCode: z.string().optional(),
    departmentCode: z.string().optional(),
    region: z.string().optional(),
    country: z
      .string()
      .optional()
      .describe(
        'Country code. Restricted to Soliguide countries for non-API users.',
      ),
  })
  .strict()
  .superRefine((location, ctx) => {
    if (location.geoType === GeoTypes.POSITION && !location.coordinates) {
      ctx.addIssue({
        code: 'custom',
        message: 'coordinates is required when geoType is position',
        path: ['coordinates'],
      });
    }

    if (
      location.geoType !== GeoTypes.POSITION &&
      location.geoType !== GeoTypes.UNKNOWN &&
      !location.geoValue
    ) {
      ctx.addIssue({
        code: 'custom',
        message: 'geoValue is required when geoType is not position or unknown',
        path: ['geoValue'],
      });
    }

    if (
      location.distance !== undefined &&
      location.geoType !== GeoTypes.POSITION
    ) {
      ctx.addIssue({
        code: 'custom',
        message: 'distance can only be used when geoType is position',
        path: ['distance'],
      });
    }
  });

const modalitiesSchema = z
  .object({
    animal: z.coerce.boolean().optional(),
    appointment: z.coerce.boolean().optional(),
    inconditionnel: z.coerce.boolean().optional(),
    inscription: z.coerce.boolean().optional(),
    orientation: z.coerce.boolean().optional(),
    pmr: z.coerce.boolean().optional(),
    price: z.coerce.boolean().optional(),
    sign: z.coerce.boolean().optional(),
  })
  .catchall(z.unknown())
  .describe(
    'Legacy modalities filter. Unknown extra keys are accepted by the route.',
  );

const publicsSchema = z
  .object({
    accueil: z.enum(WelcomedPublics).optional(),
    age: z.coerce.number().int().min(0).max(99).optional(),
    gender: z.array(z.enum(PublicsGender)).optional(),
    administrative: z.array(z.enum(PublicsAdministrative)).optional(),
    familialle: z.array(z.enum(PublicsFamily)).optional(),
    other: z.array(z.enum(PublicsOther)).optional(),
  })
  .strict()
  .describe('Public audience filters.');

const updatedAtSchema = z
  .object({
    intervalType: z.enum(UpdatedAtInterval).optional(),
    value: z.coerce.date().optional(),
  })
  .strict();

const optionsSchema = z
  .object({
    sortBy: z
      .enum([
        'createdAt',
        'lieu_id',
        'name',
        'distance',
        'slugs.infos.name',
        'status',
        'updatedAt',
      ])
      .optional(),
    sortValue: z.coerce
      .number()
      .refine((value) => value === 1 || value === -1)
      .optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
    fields: z.string().min(1).optional(),
  })
  .strict();
export const v20260101SearchRequestSchema = z
  .object({
    location: locationSchema.describe(
      'Primary location constraint (required by route validation).',
    ),
    locations: z
      .array(locationSchema)
      .optional()
      .describe(
        'Optional list of locations for widget-like multi-location search.',
      ),
    category: z.enum(Categories).optional(),
    categories: z
      .array(z.enum(Categories))
      .optional()
      .describe(
        'Multiple categories (restricted by user status at route level).',
      ),
    placeType: z
      .enum(PlaceType)
      .default(PlaceType.PLACE)
      .describe('Resource type to search: fixed places or itineraries.'),
    word: z.string().optional(),
    openToday: z.coerce
      .boolean()
      .optional()
      .describe('Only return results that are open today.')
      .meta({
        example: true,
      }),
    modalities: modalitiesSchema.optional(),
    publics: publicsSchema.optional(),
    languages: z
      .string()
      .refine((value) => PLACE_LANGUAGES_LIST_MAP_KEY.includes(value), {
        message: 'languages must be one of PLACE_LANGUAGES_LIST_MAP_KEY',
      })
      .optional(),
    widgetId: z
      .string()
      .refine(
        (value) =>
          WIDGETS_AVAILABLE.includes(
            value as (typeof WIDGETS_AVAILABLE)[number],
          ),
        {
          message: 'widgetId must be one of WIDGETS_AVAILABLE',
        },
      )
      .optional(),
    updatedAt: updatedAtSchema.optional(),
    options: optionsSchema.optional(),
  })
  .strict()
  .describe(
    'Exhaustive request body schema for POST /new-search/:lang? (non-admin route).',
  );
export type V20260101SearchRequest = z.infer<
  typeof v20260101SearchRequestSchema
>;
export type v20260101SearchRequestSchemaType = z.infer<
  typeof v20260101SearchRequestSchema
>;

export default v20260101SearchRequestSchema;
