/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import { z } from 'zod';
const locationSchema = z.object({
  address: z.string().describe('Street address of the place.').meta({
    example: '10 rue Example',
  }),
  additionalInformation: z
    .string()
    .describe(
      'Additional address details such as building, floor, or entrance.',
    )
    .meta({
      example: 'Building B, 2nd floor',
    }),
  postalCode: z.string().describe('Postal code.').meta({
    example: '75010',
  }),
  city: z.string().describe('City name.').meta({
    example: 'Paris',
  }),
  country: z
    .string()
    .describe('Country code in ISO 3166-1 alpha-2 format.')
    .meta({
      example: 'FR',
    }),
  timeZone: z.string().describe('IANA timezone of the place.').meta({
    example: 'Europe/Paris',
  }),
  department: z.string().describe('Department name (legacy field).').meta({
    example: 'Paris',
  }),
  departmentCode: z.string().describe('Department code (legacy field).').meta({
    example: '75',
  }),
  region: z.string().describe('Region name.').meta({
    example: 'Ile-de-France',
  }),
  regionCode: z.string().describe('Region code.').meta({
    example: '11',
  }),
  location: z
    .object({
      type: z.literal('Point').describe('GeoJSON point geometry type.'),
      coordinates: z
        .tuple([z.number(), z.number()])
        .describe(
          'GeoJSON coordinates [longitude, latitude] in decimal degrees.',
        )
        .meta({
          example: [2.3522, 48.8566],
        }),
    })
    .describe('Legacy GeoJSON location object.'),
});

const timeSlotSchema = z.object({
  startTime: z.iso.time(),
  endTime: z.iso.time(),
});

const openingStatusSchema = z
  .enum(['open', 'closed', 'unknown'])
  .describe('Opening status for a day or public holiday.')
  .meta({ example: 'open' });

const weeklyScheduleDaySchema = z
  .object({
    dayOfWeek: z
      .enum([
        'monday',
        'tuesday',
        'wednesday',
        'thursday',
        'friday',
        'saturday',
        'sunday',
      ])
      .describe('Days of the week.')
      .meta({ example: 'monday' }),
    status: openingStatusSchema,
    timeSlots: z
      .array(timeSlotSchema)
      .describe(
        'Opening time slots for this day. May be empty when status is closed or unknown.',
      ),
  })
  .describe('Opening information for one day of the week.');

const publicOpenedHolidaySchema = z
  .object({
    label: z
      .string()
      .describe('Human-readable name of the public holiday.')
      .meta({ example: 'New Year' }),
    status: z
      .enum(['open', 'closed'])
      .describe('Opening status for this public holiday.')
      .meta({ example: 'closed' }),
    timeSlots: z
      .array(timeSlotSchema)
      .describe('Opening time slots for this holiday when applicable.'),
  })
  .describe('Specific opening rule for one public holiday.');

const scheduleSchema = z
  .object({
    weeklySchedule: z
      .array(weeklyScheduleDaySchema)
      .describe('Weekly opening schedule.'),
    publicHolidays: z
      .object({
        status: z
          .enum(['open', 'closed', 'unknown', 'specific'])
          .describe(
            'Default public holiday behavior. Use "specific" when holiday-specific entries are provided.',
          )
          .meta({ example: 'specific' }),
        openedHolidays: z
          .array(publicOpenedHolidaySchema)
          .describe('Holiday-specific opening rules.'),
      })
      .describe('Public holiday opening information.'),
  })
  .describe('Schedule information for a place or service.');

const itineraryStopSchema = z
  .object({
    description: z
      .string()
      .nullable()
      .describe('Additional information about this stop or route point.'),
    location: locationSchema.describe(
      'Location where the itinerary service is available for this stop.',
    ),
    schedule: scheduleSchema.describe(
      'Schedule during which the itinerary service is available at this stop.',
    ),
  })
  .strict();

const fixedLocationPlaceSchema = z
  .object({
    type: z.literal('fixedLocation'),
    location: locationSchema.describe('Main location of the resource.'),
    schedule: scheduleSchema.describe('Main schedule of the resource.'),
  })
  .loose();

const itineraryPlaceSchema = z
  .object({
    type: z.literal('itinerary'),
    stops: z
      .array(itineraryStopSchema)
      .describe(
        'Scheduled stops or route points where the itinerary service is available.',
      ),
  })
  .loose();

const placeTypeDiscriminatedSchema = z
  .discriminatedUnion('type', [fixedLocationPlaceSchema, itineraryPlaceSchema])
  .meta({
    discriminator: {
      propertyName: 'type',
    },
  });
export const v20260303SearchResponseSchema = z
  .object({
    nbResults: z
      .number()
      .int()
      .min(0)
      .describe('Total number of matching places.'),
    places: z
      .array(placeTypeDiscriminatedSchema)
      .describe('List of matching place payloads.'),
  })
  .strict()
  .describe(
    'Legacy response payload for POST /new-search/:lang? excluding admin-oriented fields.',
  );
export type V20260303SearchResponse = z.infer<
  typeof v20260303SearchResponseSchema
>;
export type v20260303SearchResponseSchemaType = z.infer<
  typeof v20260303SearchResponseSchema
>;

export default v20260303SearchResponseSchema;
