/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  GeoTypes,
  PlaceClosedHolidays,
  PlaceType,
  ServiceSaturation,
} from '@soliguide/common';
import { z } from 'zod';
const emailContactSchema = z
  .object({
    type: z.literal('email').describe('Contact method type.'),
    label: z.string().describe('Display label for this contact method.').meta({
      example: 'Main email',
    }),
    value: z.email().describe('Email address.').meta({
      example: 'contact@example.org',
    }),
  })
  .meta({ title: 'Email contact' });

const phoneContactSchema = z
  .object({
    type: z.literal('phone').describe('Contact method type.'),
    label: z.string().describe('Display label for this contact method.').meta({
      example: 'Reception',
    }),
    value: z.string().describe('Phone number.').meta({
      example: '+33102030405',
    }),
  })
  .meta({ title: 'Phone contact' });

const faxContactSchema = z
  .object({
    type: z.literal('fax').describe('Contact method type.'),
    label: z.string().describe('Display label for this contact method.').meta({
      example: 'Fax',
    }),
    value: z.string().describe('Fax number.').meta({
      example: '+33102030406',
    }),
  })
  .meta({ title: 'Fax contact' });

const websiteContactSchema = z
  .object({
    type: z.literal('website').describe('Contact method type.'),
    label: z.string().describe('Display label for this contact method.').meta({
      example: 'Official website',
    }),
    value: z.url().describe('Website URL.').meta({
      example: 'https://example.org',
    }),
  })
  .meta({ title: 'Website contact' });

const socialContactSchema = z
  .object({
    type: z.literal('social').describe('Contact method type.'),
    platform: z
      .string()
      .describe('Social media platform name. Only present for social contacts.')
      .meta({
        example: 'facebook',
      }),
    label: z.string().describe('Display label for this contact method.').meta({
      example: 'Facebook page',
    }),
    value: z.url().describe('Social media profile or page URL.').meta({
      example: 'https://facebook.com/example',
    }),
  })
  .meta({ title: 'Social contact' });

const contactSchema = z
  .discriminatedUnion('type', [
    emailContactSchema,
    phoneContactSchema,
    faxContactSchema,
    websiteContactSchema,
    socialContactSchema,
  ])
  .describe('A contact method for the place or service.')
  .meta({
    discriminator: {
      propertyName: 'type',
    },
  });

type Contact = z.infer<typeof contactSchema>;
enum Category {
  health = 'Health',
  addiction = 'Addiction',
  std_testing = 'Screening',
  psychological_support = 'Psychology',
  child_care = 'Childcare',
  general_practitioner = 'General Practitioner',
  dental_care = 'Dental',
  pregnancy_care = 'Pregnancy Monitoring',
  vaccination = 'Vaccination',
  infirmary = 'Infirmary',
  vet_care = 'Veterinary',
  health_specialists = 'Specialists',
  allergology = 'Allergology',
  cardiology = 'Cardiology',
  dermatology = 'Dermatology',
  echography = 'Ultrasound',
  endocrinology = 'Endocrinology',
  gastroenterology = 'Gastroenterology',
  gynecology = 'Gynecology',
  kinesitherapy = 'Physiotherapy',
  mammography = 'Mammography',
  ophthalmology = 'Ophtalmology',
  otorhinolaryngology = 'Otorhinolaryngology',
  nutrition = 'Nutrition',
  pedicure = 'Podiatry',
  phlebology = 'Phlebology',
  pneumology = 'Pneumology',
  radiology = 'Radiology',
  rheumatology = 'Rheumatology',
  urology = 'Urology',
  speech_therapy = 'Speech Therapy',
  stomatology = 'Stomatology',
  osteopathy = 'Osteopathy',
  acupuncture = 'Acupuncture',
  mobility = 'Transportation & Mobility',
  carpooling = 'Carpooling',
  provision_of_vehicles = 'Vehicle Provision',
  chauffeur_driven_transport = 'Transport with Driver',
  mobility_assistance = 'Mobility Assistance',
  training_and_jobs = 'Training and Employment',
  digital_tools_training = 'Digital Workshop',
  french_course = 'French Classes',
  job_coaching = 'Employment Support',
  integration_through_economic_activity = 'Integration through Economic Activity',
  tutoring = 'Educational Support',
  hygiene_and_wellness = 'Hygiene and Well-being',
  shower = 'Shower',
  laundry = 'Laundry',
  wellness = 'Well-being',
  toilets = 'Toilets',
  hygiene_products = 'Hygiene Products',
  face_masks = 'Masks',
  counseling = 'Counseling',
  legal_advice = 'Legal Consultation',
  domiciliation = 'Domiciliation',
  social_accompaniment = 'Social Support',
  public_writer = 'Public Writer',
  disability_advice = 'Disability Consultation',
  administrative_assistance = 'Administrative Consultation',
  parent_assistance = 'Parental Advice',
  budget_advice = 'Budget Advice',
  technology = 'Technology',
  computers_at_your_disposal = 'Computer',
  wifi = 'Wifi',
  electrical_outlets_available = 'Outlet',
  telephone_at_your_disposal = 'Phone',
  digital_safe = 'Digital Safe',
  food = 'Food',
  food_distribution = 'Meal Distribution',
  seated_catering = 'Seated Dining',
  food_packages = 'Food Package',
  social_grocery_stores = 'Social and Solidarity Grocery',
  fountain = 'Water Fountain',
  solidarity_fridge = 'Solidarity fridge',
  shared_kitchen = 'Shared kitchen',
  cooking_workshop = 'Cooking workshop',
  baby_parcel = 'Baby parcel',
  food_voucher = 'Food voucher',
  community_garden = 'Community garden',
  welcome = 'Welcome',
  day_hosting = 'Day Center',
  rest_area = 'Rest Area',
  babysitting = 'Babysitting',
  family_area = 'Family Space',
  information_point = 'Information Point',
  activities = 'Activities',
  sport_activities = 'Sports Activities',
  museums = 'Museum',
  libraries = 'Library',
  other_activities = 'Various Activities',
  equipment = 'Equipment',
  luggage_storage = 'Luggage',
  solidarity_store = 'Solidarity Shop',
  clothing = 'Clothing',
  animal_assitance = 'Animals',
  accomodation_and_housing = 'Housing & Accommodation',
  overnight_stop = 'Night Stop',
  emergency_accommodation = 'Emergency Housing',
  long_term_accomodation = 'Long-Term Housing',
  citizen_housing = 'Citizen Housing',
  access_to_housing = 'Housing Advice',
}

const categories = Object.keys(Category);

const categoryOpenApiDescription = categories
  .map((category) => `- ${category}: ${Category[category]}`)
  .join('\n');
const requirementSchema = z.object({
  isRequired: z.boolean().describe('Whether an this requirement applies.'),
  details: z.string().nullable().describe('Additional details about'),
});

const accessSchema = z
  .object({
    isUnconditional: z
      .boolean()
      .describe(
        'If true, access to the facility is unconditional and there are no requirements',
      ),
    allowPets: z.boolean().describe('Whether pets are allowed.'),
    isWheelchairAccessible: z
      .boolean()
      .describe('Whether the place is accessible to wheelchair'),

    appointmentRequirement: requirementSchema.describe(
      'Appointement requirement.',
    ),
    registrationRequirement: requirementSchema.describe(
      'Registration requirement.',
    ),
    orientationRequirement: requirementSchema.describe(
      'Orientation requirement.',
    ),
    pricing: z.object({
      isPaid: z
        .boolean()
        .describe('Whether the place or service requires payment.')
        .meta({
          example: false,
        }),
      details: z
        .string()
        .nullable()
        .describe('Additional pricing details.')
        .meta({
          example: '2€ per meal',
        }),
    }),
    otherDetails: z
      .string()
      .nullable()
      .describe(
        'Additional free-text information related to access conditions.',
      )
      .meta({
        example: 'Bring an ID document on your first visit.',
      }),
  })
  .describe('Access rules applying to the place.');

type Access = z.infer<typeof accessSchema>;
const specialSupportContextSchema = z
  .object({
    type: z.string().describe('Broad category of support context.').meta({
      example: 'humanitarianCrisis',
    }),
    key: z
      .string()
      .describe('Stable machine-readable identifier for the support context.')
      .meta({
        example: 'ukraine-displacement',
      }),
    label: z
      .string()
      .describe('Human-readable label for the support context.')
      .meta({
        example: 'Support for displaced people from Ukraine',
      }),
    details: z
      .string()
      .describe(
        'Additional details about the support available in this context.',
      )
      .meta({
        example: 'Ukrainian-speaking volunteers available.',
      }),
  })
  .describe(
    'Special support context related to a crisis or exceptional situation.',
  );

const audienceSchema = z
  .object({
    admissionPolicy: z
      .enum(['open', 'restricted'])
      .describe(
        'Whether the place or service is open to everyone or restricted to specific audiences.',
      )
      .meta({ example: 'open' }),
    isTargeted: z
      .boolean()
      .describe(
        'Whether the place or service is designed for certain audiences, even if broad admission is open.',
      )
      .meta({ example: true }),
    description: z
      .string()
      .describe('Free-text description of the intended or accepted audience.')
      .meta({ example: 'Young adults in unstable housing.' }),
    ageRange: z
      .object({
        min: z
          .int()
          .nonnegative()
          .describe('Minimum age accepted.')
          .meta({ example: 18 }),
        max: z
          .int()
          .nonnegative()
          .describe('Maximum age accepted.')
          .meta({ example: 30 }),
      })
      .nullable()
      .describe('Age restriction. Null means there is no age restriction.')
      .meta({ example: { min: 18, max: 30 } }),
    administrativeStatuses: z
      .enum(['regular', 'asylum', 'refugee', 'undocumented'])
      .describe(
        'Accepted or targeted administrative statuses.\n- regular: Person in regular situation. \n- asylum: Person in asylum. \n- refugee: Person with refugee status. \n- undocumente: Person without passport or ID.',
      ),
    familyStatuses: z
      .enum(['isolated', 'family', 'couple', 'pregnant'])
      .describe(
        'Accepted or targeted family situations.\n- isolated: Isolated person.\n- family: Family.\n- couple: Couple.\n- pregnant: Pregnant Woman.',
      ),
    otherStatuses: z
      .enum([
        'violence',
        'addiction',
        'disability',
        'lgbt+',
        'hiv',
        'prostitution',
        'prison',
        'student',
      ])
      .describe(
        'Other accepted or targeted statuses.\n- violence: Person victim of violence.\n- addiction: Person suffering from addition.\n- disability: Person with disabilities.\n- lgbt+: Person among LGBT+ communities.\n- hiv: Person suffering from HIV.\n- prostitution: Person suffering from prostitution.\n- prison: Person getting out of prison.\n- student: Student.',
      ),
    genders: z
      .enum(['men', 'women'])
      .describe('Accepted or targeted genders.\n- men: Men.\n- women: Women'),
    specialSupportContexts: z
      .array(specialSupportContextSchema)
      .describe('Special support contexts such as crisis-specific support.'),
  })
  .describe('Audience rules and targeting information.');

type Audience = z.infer<typeof audienceSchema>;
const timeSlotSchema = z.object({
  startTime: z.iso.time(),
  endTime: z.iso.time(),
});

const openingStatusSchema = z
  .enum(['open', 'closed', 'unknown'])
  .describe('Opening status for a day or public holiday.')
  .meta({ example: 'open' });

const weeklyScheduleDaySchema = z
  .object({
    dayOfWeek: z
      .enum([
        'monday',
        'tuesday',
        'wednesday',
        'thursday',
        'friday',
        'saturday',
        'sunday',
      ])
      .describe('Days of the week.')
      .meta({ example: 'monday' }),
    status: openingStatusSchema,
    timeSlots: z
      .array(timeSlotSchema)
      .describe(
        'Opening time slots for this day. May be empty when status is closed or unknown.',
      ),
  })
  .describe('Opening information for one day of the week.');

const publicOpenedHolidaySchema = z
  .object({
    label: z
      .string()
      .describe('Human-readable name of the public holiday.')
      .meta({ example: 'New Year' }),
    status: z
      .enum(['open', 'closed'])
      .describe('Opening status for this public holiday.')
      .meta({ example: 'closed' }),
    timeSlots: z
      .array(timeSlotSchema)
      .describe('Opening time slots for this holiday when applicable.'),
  })
  .describe('Specific opening rule for one public holiday.');

const scheduleSchema = z
  .object({
    weeklySchedule: z
      .array(weeklyScheduleDaySchema)
      .describe('Weekly opening schedule.'),
    publicHolidays: z
      .object({
        status: z
          .enum(['open', 'closed', 'unknown', 'specific'])
          .describe(
            'Default public holiday behavior. Use "specific" when holiday-specific entries are provided.',
          )
          .meta({ example: 'specific' }),
        openedHolidays: z
          .array(publicOpenedHolidaySchema)
          .describe('Holiday-specific opening rules.'),
      })
      .describe('Public holiday opening information.'),
  })
  .describe('Schedule information for a place or service.');

type Schedule = z.infer<typeof scheduleSchema>;
const serviceSchema = z
  .object({
    id: z.string().describe('Unique service identifier.').meta({
      example: 'service_1',
    }),
    category: z.enum(categories).describe(categoryOpenApiDescription).meta({
      example: 'food_distribution',
    }),
    description: z.string().describe('Description of the service.').meta({
      example: 'Breakfast and hot drinks.',
    }),
    saturation: z
      .object({
        level: z
          .enum(['low', 'moderate', 'high'])
          .describe('Saturation level of the service.')
          .meta({ example: 'high' }),
        details: z
          .string()
          .nullable()
          .describe('Additional details about service saturation.')
          .meta({ example: 'Very busy on Mondays.' }),
      })
      .describe('Saturation information for the service.'),
    isOpenToday: z
      .boolean()
      .describe('Whether the service is open today')
      .meta({ example: true }),
    access: accessSchema
      .nullable()
      .describe(
        'Service-specific access rules. Null means the service inherits access rules from the place.',
      ),
    audience: audienceSchema
      .nullable()
      .describe(
        'Service-specific audience rules. Null means the service inherits audience rules from the place.',
      ),
    schedule: scheduleSchema
      .nullable()
      .describe(
        'Service-specific schedule. Null means the service inherits schedule from the place.',
      ),
  })
  .describe('Service provided by the place.');

type Service = z.infer<typeof serviceSchema>;
const locationSchema = z.object({
  address: z.string().describe('Street address of the place.').meta({
    example: '10 rue Example',
  }),
  additionalInformation: z
    .string()
    .describe(
      'Additional address details such as building, floor, or entrance.',
    )
    .meta({
      example: 'Building B, 2nd floor',
    }),
  postalCode: z.string().describe('Postal code.').meta({
    example: '75010',
  }),
  city: z.string().describe('City name.').meta({
    example: 'Paris',
  }),
  country: z
    .string()
    .describe('Country code in ISO 3166-1 alpha-2 format.')
    .meta({
      example: 'FR',
    }),
  timeZone: z.string().describe('IANA timezone of the place.').meta({
    example: 'Europe/Paris',
  }),
  department: z.string().describe('Department name (legacy field).').meta({
    example: 'Paris',
  }),
  departmentCode: z.string().describe('Department code (legacy field).').meta({
    example: '75',
  }),
  region: z.string().describe('Region name.').meta({
    example: 'Ile-de-France',
  }),
  regionCode: z.string().describe('Region code.').meta({
    example: '11',
  }),
  location: z
    .object({
      type: z.literal('Point').describe('GeoJSON point geometry type.'),
      coordinates: z
        .tuple([z.number(), z.number()])
        .describe(
          'GeoJSON coordinates [longitude, latitude] in decimal degrees.',
        )
        .meta({
          example: [2.3522, 48.8566],
        }),
    })
    .describe('Legacy GeoJSON location object.'),
});

type Location = z.infer<typeof locationSchema>;
const temporaryClosureSchema = z.object({
  startDate: z.iso
    .datetime()
    .describe(
      'Start date and time of the temporary closure in ISO 8601 format.',
    )
    .meta({
      example: '2026-04-01T00:00:00Z',
    }),
  endDate: z.iso
    .datetime()
    .describe('End date and time of the temporary closure in ISO 8601 format.')
    .meta({
      example: '2026-04-03T23:59:59Z',
    }),
  description: z
    .string()
    .describe('Explanation of the temporary closure.')
    .meta({
      example: 'Renovation work.',
    }),
});

const temporaryScheduleAdjustmentSchema = z.object({
  startDate: z.iso
    .datetime()
    .describe(
      'Start date and time of the temporary schedule adjustment in ISO 8601 format.',
    ),
  endDate: z.iso
    .datetime()
    .describe(
      'End date and time of the temporary schedule adjustment in ISO 8601 format.',
    ),
  description: z
    .string()
    .describe('Explanation of the temporary schedule adjustment.')
    .meta({
      example: 'Reduced opening hours during school holidays.',
    }),
  schedule: scheduleSchema.describe(
    'Schedule applied during the temporary adjustment period.',
  ),
});

const temporaryMessageSchema = z.object({
  title: z.string().describe('Short title of the temporary message.').meta({
    example: 'Important notice',
  }),
  startDate: z.iso
    .datetime()
    .describe(
      'Start date and time from which the message is active in ISO 8601 format.',
    ),
  endDate: z.iso
    .datetime()
    .describe(
      'End date and time until which the message is active in ISO 8601 format.',
    ),
  description: z.string().describe('Message content.').meta({
    example: 'Bring an ID document on your first visit.',
  }),
});

const temporaryInformationSchema = z
  .object({
    closures: z
      .array(temporaryClosureSchema)
      .describe('List of temporary closures affecting the place.'),
    scheduleAdjustments: z
      .array(temporaryScheduleAdjustmentSchema)
      .describe('List of temporary schedule changes affecting the place.'),
    messages: z
      .array(temporaryMessageSchema)
      .describe(
        'List of temporary informational messages displayed for the place.',
      ),
  })
  .describe(
    'Temporary operational and informational changes affecting the place.',
  );

type TemporaryInformation = z.infer<typeof temporaryInformationSchema>;
type V20260101SearchPlaceResponse = NonNullable<
  V20260101SearchResponse['places']
>[number];

type LegacyModalities = NonNullable<V20260101SearchPlaceResponse['modalities']>;

type LegacyService = NonNullable<
  V20260101SearchPlaceResponse['services_all']
>[number];

type LegacyTempInfos = NonNullable<V20260101SearchPlaceResponse['tempInfos']>;

type LegacyPublics = NonNullable<V20260101SearchPlaceResponse['publics']>;

type LegacyOpeningHours = NonNullable<V20260101SearchPlaceResponse['newhours']>;

type LegacyPosition = NonNullable<V20260101SearchPlaceResponse['position']>;

type LegacyParcours = NonNullable<V20260101SearchPlaceResponse['parcours']>;

const itineraryStopSchema = z
  .object({
    description: z
      .string()
      .nullable()
      .describe('Additional information about this stop or route point.'),
    location: locationSchema.describe(
      'Location where the itinerary service is available for this stop.',
    ),
    schedule: scheduleSchema.describe(
      'Schedule during which the itinerary service is available at this stop.',
    ),
  })
  .strict();

const fixedLocationPlaceSchema = z
  .object({
    type: z.literal('fixedLocation'),
    location: locationSchema.describe('Main location of the resource.'),
    schedule: scheduleSchema.describe('Main schedule of the resource.'),
  })
  .loose();

const itineraryPlaceSchema = z
  .object({
    type: z.literal('itinerary'),
    stops: z
      .array(itineraryStopSchema)
      .describe(
        'Scheduled stops or route points where the itinerary service is available.',
      ),
  })
  .loose();

const placeTypeDiscriminatedSchema = z
  .discriminatedUnion('type', [fixedLocationPlaceSchema, itineraryPlaceSchema])
  .meta({
    discriminator: {
      propertyName: 'type',
    },
  });

const legacyDateSchema = z.union([z.date(), z.string()]);

const legacyPositionSchema = z
  .object({
    location: z
      .object({
        type: z.literal('Point').optional(),
        coordinates: z.array(z.number()).optional(),
      })
      .strict()
      .optional(),
    address: z.string().optional(),
    additionalInformation: z.string().optional(),
    city: z.string().optional(),
    cityCode: z.string().optional(),
    postalCode: z.string().optional(),
    department: z.string().optional(),
    departmentCode: z.string().optional(),
    region: z.string().optional(),
    regionCode: z.string().optional(),
    country: z.string().optional(),
    timeZone: z.string().optional(),
    adresse: z.string().optional(),
    codePostal: z.string().optional(),
    complementAdresse: z.string().optional(),
    departement: z.string().optional(),
    pays: z.string().optional(),
    ville: z.string().optional(),
  })
  .strict();

const legacyPhotoSchema = z
  .object({
    _id: z.string().optional(),
    encoding: z.string().optional(),
    filename: z.string(),
    mimetype: z.string(),
    parcours_id: z.number().int().optional(),
    path: z.string(),
    lieu_id: z.number().int(),
    size: z.number().optional(),
    createdAt: legacyDateSchema.optional(),
    updatedAt: legacyDateSchema.optional(),
  })
  .strict();

const legacyTimeslotSchema = z
  .object({
    end: z.number().nullable().optional(),
    start: z.number().nullable().optional(),
  })
  .strict();

const legacyDayOpeningHoursSchema = z
  .object({
    open: z.boolean().optional(),
    timeslot: z.array(legacyTimeslotSchema).optional(),
  })
  .strict();

const legacyOpeningHoursSchema = z
  .object({
    closedHolidays: z.enum(PlaceClosedHolidays).optional(),
    description: z.string().nullable().optional(),
    monday: legacyDayOpeningHoursSchema.optional(),
    tuesday: legacyDayOpeningHoursSchema.optional(),
    wednesday: legacyDayOpeningHoursSchema.optional(),
    thursday: legacyDayOpeningHoursSchema.optional(),
    friday: legacyDayOpeningHoursSchema.optional(),
    saturday: legacyDayOpeningHoursSchema.optional(),
    sunday: legacyDayOpeningHoursSchema.optional(),
  })
  .strict();

const legacyModalitiesCheckSchema = z
  .object({
    checked: z.boolean().optional(),
    precisions: z.string().nullable().optional(),
  })
  .strict();

const legacyModalitiesSchema = z
  .object({
    inconditionnel: z.boolean().optional(),
    appointment: legacyModalitiesCheckSchema.optional(),
    inscription: legacyModalitiesCheckSchema.optional(),
    orientation: legacyModalitiesCheckSchema.optional(),
    price: legacyModalitiesCheckSchema.optional(),
    animal: z
      .object({
        checked: z.boolean().optional(),
      })
      .strict()
      .optional(),
    pmr: z
      .object({
        checked: z.boolean().optional(),
      })
      .strict()
      .optional(),
    docs: z.array(z.string()).optional(),
    other: z.string().nullable().optional(),
  })
  .strict();

export type LegacyModalities = z.infer<typeof legacyModalitiesSchema>;

const legacyPublicsSchema = z
  .object({
    accueil: z.union([z.literal(0), z.literal(1), z.literal(2)]).optional(),
    administrative: z.array(z.string()).optional(),
    age: z
      .object({
        max: z.number().optional(),
        min: z.number().optional(),
      })
      .strict()
      .optional(),
    description: z.string().nullable().optional(),
    familialle: z.array(z.string()).optional(),
    gender: z.array(z.string()).optional(),
    other: z.array(z.string()).optional(),
  })
  .strict();

const legacyCategorySpecificFieldsSchema = z
  .object({
    activityName: z.string().optional(),
    availableEquipmentPrecisions: z.string().optional(),
    availableEquipmentType: z.array(z.string()).optional(),
    babyParcelAgeType: z.array(z.string()).optional(),
    canteensMealType: z.string().optional(),
    courseType: z.string().optional(),
    degreeOfChoiceType: z.string().optional(),
    dietaryAdaptationsType: z.array(z.string()).optional(),
    dietaryRegimesType: z.string().optional(),
    domiciliationType: z.string().optional(),
    foodProductType: z.array(z.string()).optional(),
    otherProductTypePrecisions: z.string().optional(),
    hygieneProductType: z.string().optional(),
    jobsList: z.string().optional(),
    nationalOriginProductType: z.string().optional(),
    organicOriginProductType: z.string().optional(),
    serviceStyleType: z.array(z.string()).optional(),
    usageModality: z.string().optional(),
    voucherType: z.string().optional(),
    voucherTypePrecisions: z.string().optional(),
    wellnessActivityName: z.string().optional(),
  })
  .strict();

const legacyServiceSchema = z
  .object({
    categorie: z.number().int().optional(),
    category: z.enum(Categories),
    close: z
      .object({
        actif: z.boolean().optional(),
        dateDebut: legacyDateSchema.nullable().optional(),
        dateFin: legacyDateSchema.nullable().optional(),
      })
      .strict()
      .optional(),
    description: z.string().nullable().optional(),
    differentHours: z.boolean().optional(),
    differentModalities: z.boolean().optional(),
    differentPublics: z.boolean().optional(),
    hours: legacyOpeningHoursSchema.optional(),
    isOpenToday: z.boolean(),
    modalities: legacyModalitiesSchema.optional(),
    publics: legacyPublicsSchema.optional(),
    saturated: z
      .object({
        precision: z.string().nullable().optional(),
        status: z.enum(ServiceSaturation).optional(),
      })
      .strict()
      .optional(),
    serviceObjectId: z.string(),
    createdAt: legacyDateSchema,
    categorySpecificFields: legacyCategorySpecificFieldsSchema.optional(),
    jobsList: z.string().nullable().optional(),
    name: z.string().nullable().optional(),
  })
  .strict();

export type LegacyService = z.infer<typeof legacyServiceSchema>;

const legacyGeoZoneSchema = z
  .object({
    geoType: z.enum(GeoTypes).nullable().optional(),
    geoValue: z.string().optional(),
    label: z.string().optional(),
  })
  .strict();

const legacyTempInfoBaseSchema = z
  .object({
    actif: z.boolean().optional(),
    dateDebut: legacyDateSchema.nullable().optional(),
    dateFin: legacyDateSchema.nullable().optional(),
    description: z.string().optional(),
  })
  .strict();

const legacyTempInfoSchema = z
  .object({
    closure: legacyTempInfoBaseSchema.optional(),
    hours: legacyTempInfoBaseSchema
      .extend({
        hours: legacyOpeningHoursSchema.nullable().optional(),
      })
      .strict()
      .optional(),
    message: legacyTempInfoBaseSchema
      .extend({
        name: z.string().optional(),
      })
      .strict()
      .optional(),
  })
  .strict();

export type LegacyTempInfos = z.infer<typeof legacyTempInfoSchema>;

const legacySourceSchema = z
  .object({
    ids: z
      .array(
        z
          .object({
            id: z.string(),
            url: z.string().optional(),
          })
          .strict(),
      )
      .optional(),
    isOrigin: z.boolean(),
    license: z.string().optional(),
    name: z.string(),
  })
  .strict();

const legacyParcoursSchema = z
  .object({
    description: z.string().nullable().optional(),
    hours: legacyOpeningHoursSchema.optional(),
    position: legacyPositionSchema.nullable().optional(),
    photos: z.array(legacyPhotoSchema).optional(),
    show: z.boolean().optional(),
  })
  .strict();

const legacyPhoneSchema = z
  .object({
    label: z.string().nullable().optional(),
    phoneNumber: z.string().nullable().optional(),
    countryCode: z.string().optional(),
    isSpecialPhoneNumber: z.boolean().optional(),
  })
  .strict();

const legacyEntitySchema = z
  .object({
    facebook: z.string().optional(),
    fax: z.string().optional(),
    instagram: z.string().optional(),
    mail: z.string().optional(),
    name: z.string().nullable().optional(),
    phones: z.array(legacyPhoneSchema).optional(),
    website: z.string().nullable().optional(),
  })
  .strict();

const legacySlugsSchema = z
  .object({
    infos: z
      .object({
        description: z.string().nullable().optional(),
        name: z.string().nullable().optional(),
      })
      .strict()
      .optional(),
  })
  .strict();

export const v20260101SearchPlaceResponseSchema = z
  .object({
    name: z.string().describe('Localized name of the place.').meta({
      example: 'Community Support Center',
    }),
    description: z
      .string()
      .describe('Localized HTML content describing the place.')
      .meta({
        example:
          '<p>A support center providing food distribution and social services.</p>',
      }),
    isOpenToday: z
      .boolean()
      .describe('Whether the place is open today.')
      .meta({ example: true }),
    placeType: z.enum(PlaceType).optional(),
    position: legacyPositionSchema.optional(),
    parcours: z.array(legacyParcoursSchema).optional(),
    newhours: legacyOpeningHoursSchema.optional(),
    sourceLanguage: z.string().optional(),
    country: z.string().optional(),
    languages: z
      .array(z.string())
      .describe('Languages spoken at the place. Format ISO 639-3')
      .meta({ example: ['en', 'fr', 'rcf'] }),
    updatedAt: z.iso
      .datetime()
      .describe('Last update date and time of this place in ISO 8601 format.')
      .meta({ example: '2026-03-26T10:15:00Z' }),
    id: z.number().int().describe('Numeric place identifier.'),
    slug: z.string().describe('SEO-friendly unique slug for the place.'),
    contacts: z
      .array(contactSchema)
      .describe('Contact methods available for the place.'),
    services: z
      .array(serviceSchema)
      .describe('Services provided by the place.'),
    temporaryInformation: temporaryInformationSchema.describe(
      'Temporary changes affecting the place.',
    ),
    access: accessSchema.describe('Access rules applying to the place.'),
    audience: audienceSchema.describe(
      'Audience rules and targeting information.',
    ),
  })
  .strict()
  .describe(
    'Legacy place payload returned by POST /new-search/:lang? with admin-oriented fields removed (organizations, campaigns, createdBy, priority, stepsDone).',
  );

export const v20260303SearchResponseSchema = z
  .object({
    nbResults: z
      .number()
      .int()
      .min(0)
      .describe('Total number of matching places.'),
    places: z
      .array(placeTypeDiscriminatedSchema)
      .describe('List of matching place payloads.'),
  })
  .strict()
  .describe(
    'Legacy response payload for POST /new-search/:lang? excluding admin-oriented fields.',
  );

export type V20260101SearchPlaceResponse = z.infer<
  typeof v20260101SearchPlaceResponseSchema
>;

export type V20260101SearchResponse = z.infer<
  typeof v20260303SearchResponseSchema
>;
export type v20260303SearchResponseSchemaType = z.infer<
  typeof v20260303SearchResponseSchema
>;

export default v20260303SearchResponseSchema;
