// Doc: https://data.geopf.fr/geocodage/getCapabilities
export type PoiCategory =
  // administrative
  | "commune"
  | "epci"
  | "département"
  | "région"
  | "arrondissement municipal"
  //Transports
  | "transport"
  | "télécabine, téléphérique"
  | "transport par câble"
  | "aérodrome"
  | "héliport"
  | "altiport"
  | "parking"
  | "équipement de transport"
  | "aire de repos ou de service"
  | "gare voyageurs et fret"
  | "port"
  | "aire de triage"
  | "gare voyageurs uniquement"
  | "aérogare"
  | "arrêt voyageurs"
  | "gare téléphérique"
  | "station de métro"
  | "gare routière"
  | "station de tramway"
  | "gare fret uniquement"
  | "service dédié aux véhicules"
  | "câble transporteur"
  | "gare maritime"
  | "service dédié aux vélos"
  // residential areas
  | "zone d'habitation"
  | "château"
  | "lieu-dit habité"
  | "quartier"
  | "ruines"
  | "grange"
  | "moulin"
  | "habitat temporaire";
