export enum Origin {
  API = "API",
  LOCALHOST_DEV = "LOCALHOST_DEV",
  MOBILE_APP = "MOBILE_APP",
  ORIGIN_UNDEFINED = "ORIGIN_UNDEFINED",
  SOLIGUIDE = "SOLIGUIDE",
  SOLINUM_ORG = "SOLINUM_ORG",
  WIDGET_SOLIGUIDE = "WIDGET_SOLIGUIDE",
  WEBAPP_SOLIGUIDE = "WEBAPP_SOLIGUIDE",
}
