export const RELATIONS = [
  "API",
  "ASSOCIATION",
  "PUBLIC_SERVICE",
  "MAJOR_STAKEHOLDER",
  "AUTONOMOUS",
  "COMMON_PROJECT",
  "CO_CONSTRUCTION",
  "SPREAD_RELAY",
] as const;

export const RELATIONS_SEARCH = ["NO_RELATION", ...RELATIONS];
