export const LEGACY_SUPER_CATEGORIES_NAME_ID: Record<string, number> = {
  ACCUEIL: 700,
  ACTIVITES: 800,
  ALIMENTATION: 600,
  CONSEIL: 400,
  FORMATION_EMPLOI: 200,
  HYGIENE: 300,
  MATERIEL: 900,
  SANTE: 100,
  SPECIALISTES: 1100,
  TECHNOLOGY: 500,
  TRANSPORT_MOBILITY: 1200,
  HOUSING: 1300,
};

export const LEGACY_SUPER_CATEGORIES: number[] = Object.values(
  LEGACY_SUPER_CATEGORIES_NAME_ID
);
