import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { type SourceFile } from 'ts-morph';

const GENERATED_TS_HEADER = [
  '/**',
  ' * DO NOT EDIT: This file is generated by search-api artifact generation.',
  ' */',
  '',
].join('\n');

export class VersionedSchemaGeneratedFileWriter {
  async writeOutput(
    outputPath: string,
    workingSource: SourceFile,
  ): Promise<void> {
    const textWithHeader = this.ensureGeneratedHeader(
      workingSource.getFullText(),
    );
    const prettierConfig = (await resolveConfig(outputPath)) ?? {};
    const formatted = await format(textWithHeader, {
      ...prettierConfig,
      parser: 'typescript',
    });

    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, this.ensureTrailingNewLine(formatted), 'utf8');
  }

  private ensureGeneratedHeader(content: string): string {
    const withoutHeader = content.replace(
      /^\/\*\*[\s\S]*?generated by search-api artifact generation\.[\s\S]*?\*\/\s*/,
      '',
    );

    return `${GENERATED_TS_HEADER}${withoutHeader.trimStart()}`;
  }

  private ensureTrailingNewLine(content: string): string {
    return content.endsWith('\n') ? content : `${content}\n`;
  }
}
