import { access, mkdir, readFile, readdir, writeFile } from 'fs/promises';
import { createRequire } from 'module';
import { basename, dirname, join, resolve } from 'path';
import { z } from 'zod';
import {
  IndentationText,
  Node,
  NewLineKind,
  Project,
  QuoteKind,
  type Expression,
  type ObjectLiteralExpression,
  type PropertyAssignment,
  ts,
  SourceFile,
  CallExpression,
  SyntaxKind,
} from 'ts-morph';
import { parseObjectPath } from '../../versioning/object-path.utils';
import { readZodSchemaExpression } from '../../versioning/zod-schema-expression.utils';
import type {
  ApiVersion,
  CompiledSchemaPatch,
  CompiledVersion,
} from '../../versioning/versioning.types';

const GENERATED_TS_HEADER = [
  '/**',
  ' * DO NOT EDIT: This file is generated by search-api artifact generation.',
  ' */',
  '',
].join('\n');

export type SchemaKind = 'request' | 'response';

export interface FirstVersionSeedSource {
  sourceFilePath: string;
  exportName: string;
}

export interface GenerateVersionedSchemasResult {
  createdVersions: readonly ApiVersion[];
  schemasByVersion: ReadonlyMap<ApiVersion, z.ZodTypeAny>;
}

export class VersionedSchemaGenerator {
  private readonly changeSourceFileByClassName = new Map<string, string>();

  async generateVersionedSchemas(
    input: GenerateVersionedSchemasInput,
  ): Promise<GenerateVersionedSchemasResult> {
    if (input.supportedVersions.length === 0) {
      return {
        createdVersions: [],
        schemasByVersion: new Map<ApiVersion, z.ZodTypeAny>(),
      };
    }

    await this.assertSeedSourceExists(input.firstVersionSeed.sourceFilePath);

    const firstVersion = input.supportedVersions[0];
    const firstConstName = input.toSchemaConstName(firstVersion, input.kind);

    const standaloneSeedSource = await this.buildStandaloneSeedSource({
      sourceFilePath: input.firstVersionSeed.sourceFilePath,
      exportName: input.firstVersionSeed.exportName,
      targetConstName: firstConstName,
    });

    const createdVersions: ApiVersion[] = [];
    const schemasByVersion = new Map<ApiVersion, z.ZodTypeAny>();
    const project = this.createProject();
    const workingSourceFile = project.createSourceFile(
      '/versioned-schema.working.ts',
      standaloneSeedSource,
      { overwrite: true },
    );
    const inlinedPatchSupportModules = new Set<string>();
    const patchSupportInsertionIndex = {
      value: workingSourceFile.getImportDeclarations().length,
    };

    for (let index = 0; index < input.supportedVersions.length; index += 1) {
      const version = input.supportedVersions[index];
      const compiledVersion = input.compiledVersions[index];
      if (!compiledVersion || compiledVersion.version !== version) {
        throw new Error(
          `Missing compiled version payload for ${version} while generating ${input.kind} schema artifacts.`,
        );
      }

      const schemaConstName = input.toSchemaConstName(version, input.kind);

      if (index > 0) {
        const previousVersion = input.supportedVersions[index - 1];
        const previousConstName = input.toSchemaConstName(
          previousVersion,
          input.kind,
        );

        this.renameSchemaModuleIdentifiers(
          workingSourceFile,
          previousConstName,
          schemaConstName,
        );

        const changes =
          input.kind === 'request'
            ? compiledVersion.requestChanges
            : compiledVersion.responseChanges;

        for (const change of changes) {
          await this.inlinePatchSupportModules(
            workingSourceFile,
            change,
            inlinedPatchSupportModules,
            patchSupportInsertionIndex,
          );
          this.applySchemaPatch(
            workingSourceFile,
            schemaConstName,
            change.schemaPatch,
          );
        }
      }

      this.assertNoRelativeImports(
        workingSourceFile,
        `schema ${schemaConstName} (${version})`,
      );

      workingSourceFile.formatText();

      const output = ensureTrailingNewline(
        ensureGeneratedTsHeader(workingSourceFile.getFullText()),
      );
      const outputPath = input.schemaFilePathForVersion(version, input.kind);
      await mkdir(dirname(outputPath), { recursive: true });
      await writeFile(outputPath, output, 'utf8');

      const generatedSchema = this.readSchemaFromSourceFile(
        workingSourceFile,
        schemaConstName,
        version,
      );
      createdVersions.push(version);
      schemasByVersion.set(version, generatedSchema);
    }

    return {
      createdVersions,
      schemasByVersion,
    };
  }

  private async buildStandaloneSeedSource(input: {
    sourceFilePath: string;
    exportName: string;
    targetConstName: string;
  }): Promise<string> {
    const normalizedSourcePath = resolve(input.sourceFilePath);
    const project = this.createProject();
    const orderedPaths = await this.collectLocalModuleClosure(
      project,
      normalizedSourcePath,
    );

    const standaloneProject = this.createProject();
    const importAccumulator = new ExternalImportAccumulator();
    const statementChunks: string[] = [];

    for (const modulePath of orderedPaths) {
      const sourceFile = project.getSourceFileOrThrow(modulePath);
      const isEntry = modulePath === normalizedSourcePath;

      for (const importDeclaration of sourceFile.getImportDeclarations()) {
        if (isTypeOnlyImportDeclaration(importDeclaration)) {
          continue;
        }

        const moduleSpecifier = importDeclaration.getModuleSpecifierValue();
        if (isRelativeModuleSpecifier(moduleSpecifier)) {
          continue;
        }

        importAccumulator.addImportDeclaration(importDeclaration);
      }

      const workingModule = standaloneProject.createSourceFile(
        `/inlined/${basename(modulePath)}.${statementChunks.length}.ts`,
        sourceFile.getFullText(),
        { overwrite: true },
      );

      this.stripModuleForInlining(workingModule, isEntry);

      const moduleStatementText = workingModule
        .getStatements()
        .map((statement) => statement.getText())
        .join('\n\n')
        .trim();

      if (moduleStatementText.length > 0) {
        statementChunks.push(moduleStatementText);
      }
    }

    const assembledSourceText = [importAccumulator.render(), ...statementChunks]
      .filter((chunk) => chunk.trim().length > 0)
      .join('\n\n');

    const assembledSourceFile = standaloneProject.createSourceFile(
      '/standalone.seed.ts',
      assembledSourceText,
      { overwrite: true },
    );

    this.renameSchemaModuleIdentifiers(
      assembledSourceFile,
      input.exportName,
      input.targetConstName,
    );
    this.assertNoRelativeImports(
      assembledSourceFile,
      `standalone seed ${input.targetConstName}`,
    );

    assembledSourceFile.formatText();

    return ensureTrailingNewline(
      ensureGeneratedTsHeader(assembledSourceFile.getFullText()),
    );
  }

  private async inlinePatchSupportModules(
    workingSourceFile: SourceFile,
    change: Pick<
      CompiledVersion['requestChanges'][number],
      'sourceFilePath' | 'changeClassName'
    >,
    inlinedModulePaths: Set<string>,
    insertionIndex: { value: number },
  ): Promise<void> {
    const normalizedSourcePath = await this.resolveExistingSourceFilePath(
      change.sourceFilePath,
      change.changeClassName,
    );
    if (!normalizedSourcePath) {
      return;
    }

    const project = this.createProject();
    const orderedPaths = await this.collectLocalModuleClosure(
      project,
      normalizedSourcePath,
    );
    const inlineProject = this.createProject();

    for (const modulePath of orderedPaths) {
      if (inlinedModulePaths.has(modulePath)) {
        continue;
      }

      const sourceFile = project.getSourceFileOrThrow(modulePath);
      const isEntry = modulePath === normalizedSourcePath;
      const workingModule = inlineProject.createSourceFile(
        `/patch-support/${basename(modulePath)}.${inlinedModulePaths.size}.ts`,
        sourceFile.getFullText(),
        { overwrite: true },
      );

      this.stripModuleForPatchSupportInlining(workingModule, isEntry);

      const statementText = workingModule
        .getStatements()
        .map((statement) => statement.getText())
        .join('\n\n')
        .trim();

      if (statementText.length > 0) {
        const insertedStatements = workingSourceFile.insertStatements(
          insertionIndex.value,
          statementText,
        );
        insertionIndex.value += insertedStatements.length;
      }

      inlinedModulePaths.add(modulePath);
    }
  }

  private async collectLocalModuleClosure(
    project: Project,
    entryFilePath: string,
  ): Promise<readonly string[]> {
    const orderedPaths: string[] = [];
    const visited = new Set<string>();
    const inStack = new Set<string>();

    const walk = async (filePath: string): Promise<void> => {
      const normalizedPath = resolve(filePath);
      if (visited.has(normalizedPath)) {
        return;
      }

      if (inStack.has(normalizedPath)) {
        throw new Error(
          `Circular local import detected while inlining schema seed source at "${normalizedPath}".`,
        );
      }

      inStack.add(normalizedPath);
      const sourceFile = await this.loadSourceFile(project, normalizedPath);

      for (const importDeclaration of sourceFile.getImportDeclarations()) {
        if (isTypeOnlyImportDeclaration(importDeclaration)) {
          continue;
        }

        const moduleSpecifier = importDeclaration.getModuleSpecifierValue();
        if (!isRelativeModuleSpecifier(moduleSpecifier)) {
          continue;
        }

        const dependencyPath = await resolveLocalModuleFilePath(
          normalizedPath,
          moduleSpecifier,
        );
        await walk(dependencyPath);
      }

      inStack.delete(normalizedPath);
      visited.add(normalizedPath);
      orderedPaths.push(normalizedPath);
    };

    await walk(entryFilePath);

    return orderedPaths;
  }

  private async loadSourceFile(
    project: Project,
    filePath: string,
  ): Promise<SourceFile> {
    const existing = project.getSourceFile(filePath);
    if (existing) {
      return existing;
    }

    let sourceText: string;
    try {
      sourceText = await readFile(filePath, 'utf8');
    } catch {
      throw new Error(
        `Could not read schema seed source file at "${filePath}" while building standalone artifacts.`,
      );
    }

    return project.createSourceFile(filePath, sourceText, { overwrite: true });
  }

  private stripModuleForInlining(
    sourceFile: SourceFile,
    isEntry: boolean,
  ): void {
    for (const importDeclaration of sourceFile.getImportDeclarations()) {
      importDeclaration.remove();
    }

    for (const exportDeclaration of sourceFile.getExportDeclarations()) {
      exportDeclaration.remove();
    }

    if (!isEntry) {
      for (const exportAssignment of sourceFile.getExportAssignments()) {
        exportAssignment.remove();
      }
    }

    if (isEntry) {
      return;
    }

    for (const statement of sourceFile.getStatements()) {
      if (Node.isVariableStatement(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isFunctionDeclaration(statement)) {
        statement.setIsExported(false);
        statement.setIsDefaultExport(false);
        continue;
      }

      if (Node.isClassDeclaration(statement)) {
        statement.setIsExported(false);
        statement.setIsDefaultExport(false);
        continue;
      }

      if (Node.isInterfaceDeclaration(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isTypeAliasDeclaration(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isEnumDeclaration(statement)) {
        statement.setIsExported(false);
      }
    }
  }

  private stripModuleForPatchSupportInlining(
    sourceFile: SourceFile,
    isEntry: boolean,
  ): void {
    for (const importDeclaration of sourceFile.getImportDeclarations()) {
      importDeclaration.remove();
    }

    for (const exportDeclaration of sourceFile.getExportDeclarations()) {
      exportDeclaration.remove();
    }

    for (const exportAssignment of sourceFile.getExportAssignments()) {
      exportAssignment.remove();
    }

    for (const statement of sourceFile.getStatements()) {
      if (Node.isClassDeclaration(statement)) {
        statement.remove();
        continue;
      }

      if (Node.isVariableStatement(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isFunctionDeclaration(statement)) {
        statement.setIsExported(false);
        statement.setIsDefaultExport(false);
        continue;
      }

      if (Node.isInterfaceDeclaration(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isTypeAliasDeclaration(statement)) {
        statement.setIsExported(false);
        continue;
      }

      if (Node.isEnumDeclaration(statement)) {
        statement.setIsExported(false);
      }
    }

    if (isEntry) {
      return;
    }
  }

  private async resolveExistingSourceFilePath(
    sourceFilePath: string | undefined,
    changeClassName?: string,
  ): Promise<string | undefined> {
    const explicitSourcePath = await this.tryResolveSourcePath(sourceFilePath);
    if (explicitSourcePath && this.isSchemaSourcePath(explicitSourcePath)) {
      return explicitSourcePath;
    }

    if (!changeClassName) {
      return undefined;
    }

    const cached = this.changeSourceFileByClassName.get(changeClassName);
    if (cached) {
      return cached;
    }

    const discovered =
      await this.findChangeSourceFileByClassName(changeClassName);
    if (discovered) {
      this.changeSourceFileByClassName.set(changeClassName, discovered);
    }

    return discovered;
  }

  private isSchemaSourcePath(filePath: string): boolean {
    return /[/\\]app[/\\]api[/\\]schema[/\\]/u.test(filePath);
  }

  private async tryResolveSourcePath(
    sourceFilePath: string | undefined,
  ): Promise<string | undefined> {
    if (!sourceFilePath || sourceFilePath.trim().length === 0) {
      return undefined;
    }

    const normalizedInput = sourceFilePath.startsWith('file://')
      ? sourceFilePath.slice('file://'.length)
      : sourceFilePath;
    const absoluteInput = resolve(normalizedInput);
    const candidates = absoluteInput.endsWith('.ts')
      ? [absoluteInput]
      : absoluteInput.endsWith('.js')
        ? [absoluteInput.replace(/\.js$/u, '.ts'), absoluteInput]
        : [`${absoluteInput}.ts`, `${absoluteInput}.js`, absoluteInput];

    for (const candidate of candidates) {
      try {
        await access(candidate);
        return resolve(candidate);
      } catch {
        // Keep trying candidate paths.
      }
    }

    return undefined;
  }

  private async findChangeSourceFileByClassName(
    changeClassName: string,
  ): Promise<string | undefined> {
    const sourceRoots = await this.resolveSchemaSourceRoots();
    const classPattern = new RegExp(
      `class\\s+${escapeRegExp(changeClassName)}\\b`,
    );

    for (const sourceRoot of sourceRoots) {
      const candidates = await this.listTypeScriptFiles(sourceRoot);
      for (const candidate of candidates) {
        if (candidate.endsWith('.generated.ts')) {
          continue;
        }

        let sourceText: string;
        try {
          sourceText = await readFile(candidate, 'utf8');
        } catch {
          continue;
        }

        if (classPattern.test(sourceText)) {
          return candidate;
        }
      }
    }

    return undefined;
  }

  private async resolveSchemaSourceRoots(): Promise<readonly string[]> {
    const roots = [
      resolve(process.cwd(), 'src/app/api/schema'),
      resolve(process.cwd(), 'packages/public-api/src/app/api/schema'),
      resolve(__dirname, '../../../app/api/schema'),
      resolve(__dirname, '../../../../app/api/schema'),
    ];
    const existingRoots: string[] = [];

    for (const root of roots) {
      try {
        await access(root);
        existingRoots.push(root);
      } catch {
        // Ignore missing roots.
      }
    }

    return [...new Set(existingRoots)];
  }

  private async listTypeScriptFiles(rootDirectory: string): Promise<string[]> {
    const files: string[] = [];
    const stack = [rootDirectory];

    while (stack.length > 0) {
      const current = stack.pop();
      if (!current) {
        continue;
      }

      const entries = await this.readDirectoryEntries(current);
      if (!entries) {
        continue;
      }

      for (const entry of entries) {
        const entryPath = join(current, entry.name);
        if (entry.isDirectory()) {
          stack.push(entryPath);
          continue;
        }

        if (entry.isFile() && entry.name.endsWith('.ts')) {
          files.push(entryPath);
        }
      }
    }

    return files;
  }

  private async readDirectoryEntries(
    directoryPath: string,
  ): Promise<readonly import('fs').Dirent[] | undefined> {
    try {
      return await readdir(directoryPath, {
        withFileTypes: true,
        encoding: 'utf8',
      });
    } catch {
      return undefined;
    }
  }

  private async assertSeedSourceExists(seedSourcePath: string): Promise<void> {
    try {
      await access(seedSourcePath);
    } catch {
      throw new Error(
        `Missing first-version schema seed source file: ${basename(seedSourcePath)}.`,
      );
    }
  }

  private assertNoRelativeImports(sourceFile: SourceFile, scope: string): void {
    const relativeImport = sourceFile
      .getImportDeclarations()
      .find((importDeclaration) =>
        isRelativeModuleSpecifier(importDeclaration.getModuleSpecifierValue()),
      );

    if (!relativeImport) {
      return;
    }

    throw new Error(
      `Generated standalone schema invariant violated for ${scope}: relative import "${relativeImport.getModuleSpecifierValue()}" is not allowed.`,
    );
  }

  private createProject(): Project {
    return new Project({
      manipulationSettings: {
        indentationText: IndentationText.TwoSpaces,
        newLineKind: NewLineKind.LineFeed,
        quoteKind: QuoteKind.Single,
        useTrailingCommas: true,
      },
      useInMemoryFileSystem: true,
    });
  }

  private renameSchemaModuleIdentifiers(
    sourceFile: SourceFile,
    previousConstName: string,
    nextConstName: string,
  ): void {
    const constDeclaration =
      sourceFile.getVariableDeclaration(previousConstName);

    if (!constDeclaration) {
      throw new Error(
        `Could not find schema const "${previousConstName}" in seed schema file.`,
      );
    }

    constDeclaration.rename(nextConstName);

    const variableStatement = constDeclaration.getVariableStatement();
    variableStatement?.setIsExported(true);

    const previousTypeName = `${previousConstName}Type`;
    const nextTypeName = `${nextConstName}Type`;
    const typeAlias = sourceFile.getTypeAlias(previousTypeName);

    if (typeAlias) {
      typeAlias.rename(nextTypeName);
      typeAlias.setIsExported(true);
    } else if (!sourceFile.getTypeAlias(nextTypeName)) {
      sourceFile.addTypeAlias({
        isExported: true,
        name: nextTypeName,
        type: `z.infer<typeof ${nextConstName}>`,
      });
    }

    const exportAssignments = sourceFile
      .getExportAssignments()
      .filter((assignment) => !assignment.isExportEquals());

    const defaultExport = exportAssignments[0];
    if (defaultExport) {
      defaultExport.setExpression(nextConstName);
      return;
    }

    sourceFile.addExportAssignment({
      expression: nextConstName,
      isExportEquals: false,
    });
  }

  private applySchemaPatch(
    sourceFile: SourceFile,
    schemaConstName: string,
    patch: CompiledSchemaPatch,
  ): void {
    const declaration = sourceFile.getVariableDeclaration(schemaConstName);
    if (!declaration) {
      throw new Error(
        `Schema const "${schemaConstName}" not found while applying payloadPath "${patch.payloadPath}".`,
      );
    }

    const initializer = declaration.getInitializer();
    if (!initializer || !Node.isExpression(initializer)) {
      throw new Error(
        `Schema const "${schemaConstName}" must define a valid initializer expression.`,
      );
    }

    const tokens = parseObjectPath(patch.payloadPath, { allowWildcard: true });

    if (patch.replace) {
      const replacementText = resolveSchemaInitializerExpression(
        patch.replace.zod,
      );
      validateSchemaInitializerExpression(replacementText);

      const currentInitializer = declaration.getInitializer();
      if (!currentInitializer || !Node.isExpression(currentInitializer)) {
        throw new Error(
          `Schema const "${schemaConstName}" must define a valid initializer expression.`,
        );
      }

      const targetExpression = this.resolveExpressionAtPath(
        currentInitializer,
        tokens,
        patch.payloadPath,
        schemaConstName,
      );
      targetExpression.replaceWithText(replacementText);
    }

    const hasObjectPatch =
      (patch.remove ?? []).length > 0 || Boolean(patch.set);

    if (!hasObjectPatch) {
      return;
    }

    const patchedInitializer = declaration.getInitializer();
    if (!patchedInitializer || !Node.isExpression(patchedInitializer)) {
      throw new Error(
        `Schema const "${schemaConstName}" must define a valid initializer expression.`,
      );
    }

    const targetObjectLiteral = this.resolveObjectLiteralAtPath(
      patchedInitializer,
      tokens,
      patch.payloadPath,
      schemaConstName,
    );

    for (const field of patch.remove ?? []) {
      const existingProperty = findPropertyAssignment(
        targetObjectLiteral,
        field,
      );
      existingProperty?.remove();
    }

    for (const [field, spec] of Object.entries(patch.set ?? {})) {
      const initializerText = resolveSchemaInitializerExpression(spec.zod);
      validateSchemaInitializerExpression(initializerText);
      const existingProperty = findPropertyAssignment(
        targetObjectLiteral,
        field,
      );

      if (existingProperty) {
        existingProperty.setInitializer(initializerText);
        continue;
      }

      targetObjectLiteral.addPropertyAssignment({
        name: formatPropertyName(field),
        initializer: initializerText,
      });
    }
  }

  private resolveExpressionAtPath(
    schemaExpression: Expression,
    tokens: readonly string[],
    payloadPath: string,
    schemaConstName: string,
  ): Expression {
    if (tokens.length === 0) {
      return this.unwrapParenthesizedExpression(schemaExpression);
    }

    const [head, ...rest] = tokens;

    if (head === '*') {
      const elementExpression = this.extractArrayElementExpression(
        schemaExpression,
        payloadPath,
        schemaConstName,
      );
      return this.resolveExpressionAtPath(
        elementExpression,
        rest,
        payloadPath,
        schemaConstName,
      );
    }

    const objectShape = this.extractObjectShapeLiteral(
      schemaExpression,
      payloadPath,
      schemaConstName,
    );
    const property = findPropertyAssignment(objectShape, head);

    if (!property) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Missing segment "${head}" in schema "${schemaConstName}".`,
      );
    }

    const initializer = property.getInitializer();
    if (!initializer || !Node.isExpression(initializer)) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Segment "${head}" has no initializer expression.`,
      );
    }

    return this.resolveExpressionAtPath(
      initializer,
      rest,
      payloadPath,
      schemaConstName,
    );
  }

  private resolveObjectLiteralAtPath(
    schemaExpression: Expression,
    tokens: readonly string[],
    payloadPath: string,
    schemaConstName: string,
  ): ObjectLiteralExpression {
    if (tokens.length === 0) {
      return this.extractObjectShapeLiteral(
        schemaExpression,
        payloadPath,
        schemaConstName,
      );
    }

    const [head, ...rest] = tokens;

    if (head === '*') {
      const elementExpression = this.extractArrayElementExpression(
        schemaExpression,
        payloadPath,
        schemaConstName,
      );
      return this.resolveObjectLiteralAtPath(
        elementExpression,
        rest,
        payloadPath,
        schemaConstName,
      );
    }

    const objectShape = this.extractObjectShapeLiteral(
      schemaExpression,
      payloadPath,
      schemaConstName,
    );
    const property = findPropertyAssignment(objectShape, head);

    if (!property) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Missing segment "${head}" in schema "${schemaConstName}".`,
      );
    }

    const initializer = property.getInitializer();
    if (!initializer || !Node.isExpression(initializer)) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Segment "${head}" has no initializer expression.`,
      );
    }

    return this.resolveObjectLiteralAtPath(
      initializer,
      rest,
      payloadPath,
      schemaConstName,
    );
  }

  private extractObjectShapeLiteral(
    expression: Expression,
    payloadPath: string,
    schemaConstName: string,
  ): ObjectLiteralExpression {
    const unwrapped = this.unwrapParenthesizedExpression(expression);

    if (Node.isIdentifier(unwrapped)) {
      const resolved = this.resolveIdentifierInitializerExpression(
        unwrapped,
        payloadPath,
        schemaConstName,
      );
      return this.extractObjectShapeLiteral(
        resolved,
        payloadPath,
        schemaConstName,
      );
    }

    if (Node.isCallExpression(unwrapped)) {
      const callee = unwrapped.getExpression();

      if (this.isZodFactoryCall(unwrapped, 'object')) {
        const firstArgument = unwrapped.getArguments()[0];
        if (!firstArgument || !Node.isObjectLiteralExpression(firstArgument)) {
          breakInvalidObject(payloadPath, schemaConstName);
        }

        return firstArgument;
      }

      if (Node.isPropertyAccessExpression(callee)) {
        return this.extractObjectShapeLiteral(
          callee.getExpression(),
          payloadPath,
          schemaConstName,
        );
      }
    }

    breakInvalidObject(payloadPath, schemaConstName);
  }

  private extractArrayElementExpression(
    expression: Expression,
    payloadPath: string,
    schemaConstName: string,
  ): Expression {
    const unwrapped = this.unwrapParenthesizedExpression(expression);

    if (Node.isIdentifier(unwrapped)) {
      const resolved = this.resolveIdentifierInitializerExpression(
        unwrapped,
        payloadPath,
        schemaConstName,
      );
      return this.extractArrayElementExpression(
        resolved,
        payloadPath,
        schemaConstName,
      );
    }

    if (Node.isCallExpression(unwrapped)) {
      const callee = unwrapped.getExpression();

      if (this.isZodFactoryCall(unwrapped, 'array')) {
        const firstArgument = unwrapped.getArguments()[0];
        if (firstArgument && Node.isExpression(firstArgument)) {
          return firstArgument;
        }

        breakInvalidArray(payloadPath, schemaConstName);
      }

      if (Node.isPropertyAccessExpression(callee)) {
        return this.extractArrayElementExpression(
          callee.getExpression(),
          payloadPath,
          schemaConstName,
        );
      }
    }

    breakInvalidArray(payloadPath, schemaConstName);
  }

  private resolveIdentifierInitializerExpression(
    identifier: Expression,
    payloadPath: string,
    schemaConstName: string,
  ): Expression {
    if (!Node.isIdentifier(identifier)) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Could not resolve identifier in schema "${schemaConstName}".`,
      );
    }

    const sourceFile = identifier.getSourceFile();
    const declaration = sourceFile.getVariableDeclaration(identifier.getText());
    if (!declaration) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Could not resolve identifier "${identifier.getText()}" in schema "${schemaConstName}".`,
      );
    }

    const initializer = declaration.getInitializer();
    if (!initializer || !Node.isExpression(initializer)) {
      throw new Error(
        `Invalid payloadPath "${payloadPath}". Identifier "${identifier.getText()}" has no initializer expression in schema "${schemaConstName}".`,
      );
    }

    return this.unwrapParenthesizedExpression(initializer);
  }

  private unwrapParenthesizedExpression(expression: Expression): Expression {
    let cursor: Expression = expression;

    while (Node.isParenthesizedExpression(cursor)) {
      const inner = cursor.getExpression();
      if (!Node.isExpression(inner)) {
        break;
      }

      cursor = inner;
    }

    return cursor;
  }

  private isZodFactoryCall(
    callExpression: CallExpression,
    factoryName: 'object' | 'array',
  ): boolean {
    const callee = callExpression.getExpression();
    if (!Node.isPropertyAccessExpression(callee)) {
      return false;
    }

    if (callee.getName() !== factoryName) {
      return false;
    }

    const target = callee.getExpression();
    return Node.isIdentifier(target) && target.getText() === 'z';
  }

  private readSchemaFromSourceFile(
    sourceFile: SourceFile,
    schemaConstName: string,
    version: ApiVersion,
  ): z.ZodTypeAny {
    return evaluateSchemaModuleExport(
      sourceFile.getFullText(),
      schemaConstName,
      version,
    );
  }
}

interface GenerateVersionedSchemasInput {
  supportedVersions: readonly ApiVersion[];
  compiledVersions: readonly CompiledVersion[];
  kind: SchemaKind;
  toSchemaConstName(version: ApiVersion, kind: SchemaKind): string;
  schemaFilePathForVersion(version: ApiVersion, kind: SchemaKind): string;
  firstVersionSeed: FirstVersionSeedSource;
}

interface NamedImportSpec {
  importedName: string;
  localName: string;
}

interface ModuleImportSpec {
  defaultImport?: string;
  namespaceImport?: string;
  namedImports: Map<string, NamedImportSpec>;
  sideEffectOnly: boolean;
}

class ExternalImportAccumulator {
  private readonly byModule = new Map<string, ModuleImportSpec>();
  private readonly localBindingToModule = new Map<string, string>();

  addImportDeclaration(
    importDeclaration: import('ts-morph').ImportDeclaration,
  ): void {
    const moduleSpecifier = importDeclaration.getModuleSpecifierValue();
    const importClause = importDeclaration.getImportClause();

    if (!importClause) {
      const spec = this.getOrCreateModuleSpec(moduleSpecifier);
      spec.sideEffectOnly = true;
      return;
    }

    if (moduleSpecifier === 'zod') {
      const defaultImport = importDeclaration.getDefaultImport();
      if (defaultImport && defaultImport.getText() === 'z') {
        this.addNamedImport(moduleSpecifier, 'z', 'z');
      } else if (defaultImport) {
        this.addDefaultImport(moduleSpecifier, defaultImport.getText());
      }
    } else {
      const defaultImport = importDeclaration.getDefaultImport();
      if (defaultImport) {
        this.addDefaultImport(moduleSpecifier, defaultImport.getText());
      }
    }

    const namespaceImport = importClause.getNamespaceImport();
    if (namespaceImport) {
      this.addNamespaceImport(moduleSpecifier, namespaceImport.getText());
    }

    for (const namedImport of importClause.getNamedImports()) {
      const importedName = namedImport.getNameNode().getText();
      const localName = namedImport.getAliasNode()?.getText() ?? importedName;
      this.addNamedImport(moduleSpecifier, importedName, localName);
    }
  }

  render(): string {
    const importLines: string[] = [];

    const modules = [...this.byModule.keys()].sort();
    for (const moduleSpecifier of modules) {
      const spec = this.byModule.get(moduleSpecifier);
      if (!spec) {
        continue;
      }

      const namedImports = [...spec.namedImports.values()].sort((a, b) =>
        a.localName.localeCompare(b.localName),
      );

      if (
        spec.sideEffectOnly &&
        !spec.defaultImport &&
        !spec.namespaceImport &&
        namedImports.length === 0
      ) {
        importLines.push(`import '${moduleSpecifier}';`);
        continue;
      }

      if (spec.namespaceImport && namedImports.length > 0) {
        const namespaceClause = spec.defaultImport
          ? `${spec.defaultImport}, * as ${spec.namespaceImport}`
          : `* as ${spec.namespaceImport}`;
        importLines.push(
          `import ${namespaceClause} from '${moduleSpecifier}';`,
        );

        const namedClause = namedImports
          .map((namedImport) =>
            namedImport.importedName === namedImport.localName
              ? namedImport.importedName
              : `${namedImport.importedName} as ${namedImport.localName}`,
          )
          .join(', ');
        importLines.push(
          `import { ${namedClause} } from '${moduleSpecifier}';`,
        );
        continue;
      }

      if (spec.namespaceImport) {
        const clause = spec.defaultImport
          ? `${spec.defaultImport}, * as ${spec.namespaceImport}`
          : `* as ${spec.namespaceImport}`;
        importLines.push(`import ${clause} from '${moduleSpecifier}';`);
        continue;
      }

      const namedClause = namedImports
        .map((namedImport) =>
          namedImport.importedName === namedImport.localName
            ? namedImport.importedName
            : `${namedImport.importedName} as ${namedImport.localName}`,
        )
        .join(', ');

      if (spec.defaultImport && namedClause.length > 0) {
        importLines.push(
          `import ${spec.defaultImport}, { ${namedClause} } from '${moduleSpecifier}';`,
        );
        continue;
      }

      if (spec.defaultImport) {
        importLines.push(
          `import ${spec.defaultImport} from '${moduleSpecifier}';`,
        );
        continue;
      }

      if (namedClause.length > 0) {
        importLines.push(
          `import { ${namedClause} } from '${moduleSpecifier}';`,
        );
      }
    }

    return importLines.join('\n');
  }

  private addDefaultImport(moduleSpecifier: string, localName: string): void {
    const existingModule = this.localBindingToModule.get(localName);
    if (existingModule && existingModule !== moduleSpecifier) {
      throw new Error(
        `Cannot inline schema seed sources: import binding "${localName}" conflicts between modules "${existingModule}" and "${moduleSpecifier}".`,
      );
    }

    const spec = this.getOrCreateModuleSpec(moduleSpecifier);

    if (spec.namedImports.has(localName)) {
      return;
    }

    if (!spec.defaultImport) {
      spec.defaultImport = localName;
      this.localBindingToModule.set(localName, moduleSpecifier);
      return;
    }

    if (spec.defaultImport !== localName) {
      throw new Error(
        `Cannot inline schema seed sources: multiple default imports for "${moduleSpecifier}" with different local names ("${spec.defaultImport}", "${localName}").`,
      );
    }
  }

  private addNamespaceImport(moduleSpecifier: string, localName: string): void {
    const existingModule = this.localBindingToModule.get(localName);
    if (existingModule && existingModule !== moduleSpecifier) {
      throw new Error(
        `Cannot inline schema seed sources: import binding "${localName}" conflicts between modules "${existingModule}" and "${moduleSpecifier}".`,
      );
    }

    const spec = this.getOrCreateModuleSpec(moduleSpecifier);
    if (!spec.namespaceImport) {
      spec.namespaceImport = localName;
      this.localBindingToModule.set(localName, moduleSpecifier);
      return;
    }

    if (spec.namespaceImport !== localName) {
      throw new Error(
        `Cannot inline schema seed sources: multiple namespace imports for "${moduleSpecifier}" with different local names ("${spec.namespaceImport}", "${localName}").`,
      );
    }
  }

  private addNamedImport(
    moduleSpecifier: string,
    importedName: string,
    localName: string,
  ): void {
    const existingModule = this.localBindingToModule.get(localName);
    if (existingModule && existingModule !== moduleSpecifier) {
      throw new Error(
        `Cannot inline schema seed sources: import binding "${localName}" conflicts between modules "${existingModule}" and "${moduleSpecifier}".`,
      );
    }

    const spec = this.getOrCreateModuleSpec(moduleSpecifier);

    if (spec.defaultImport === localName) {
      spec.defaultImport = undefined;
    }

    const existing = spec.namedImports.get(localName);
    if (existing) {
      if (existing.importedName !== importedName) {
        throw new Error(
          `Cannot inline schema seed sources: named import "${localName}" from "${moduleSpecifier}" is bound to both "${existing.importedName}" and "${importedName}".`,
        );
      }

      return;
    }

    spec.namedImports.set(localName, {
      importedName,
      localName,
    });
    this.localBindingToModule.set(localName, moduleSpecifier);
  }

  private getOrCreateModuleSpec(moduleSpecifier: string): ModuleImportSpec {
    const existing = this.byModule.get(moduleSpecifier);
    if (existing) {
      return existing;
    }

    const created: ModuleImportSpec = {
      namedImports: new Map<string, NamedImportSpec>(),
      sideEffectOnly: false,
    };
    this.byModule.set(moduleSpecifier, created);
    return created;
  }
}

function isRelativeModuleSpecifier(moduleSpecifier: string): boolean {
  return moduleSpecifier.startsWith('./') || moduleSpecifier.startsWith('../');
}

function isTypeOnlyImportDeclaration(
  importDeclaration: import('ts-morph').ImportDeclaration,
): boolean {
  if (importDeclaration.isTypeOnly()) {
    return true;
  }

  const importClause = importDeclaration.getImportClause();
  if (!importClause) {
    return false;
  }

  if (importClause.getDefaultImport() || importClause.getNamespaceImport()) {
    return false;
  }

  const namedImports = importClause.getNamedImports();
  return (
    namedImports.length > 0 &&
    namedImports.every((namedImport) => namedImport.isTypeOnly())
  );
}

async function resolveLocalModuleFilePath(
  fromFilePath: string,
  moduleSpecifier: string,
): Promise<string> {
  const fromDirectory = dirname(fromFilePath);
  const candidateBase = resolve(fromDirectory, moduleSpecifier);
  const candidates = candidateBase.endsWith('.ts')
    ? [candidateBase]
    : [`${candidateBase}.ts`, join(candidateBase, 'index.ts'), candidateBase];

  for (const candidate of candidates) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      // Keep trying candidates.
    }
  }

  throw new Error(
    `Could not resolve local schema seed import "${moduleSpecifier}" from "${fromFilePath}".`,
  );
}

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function formatPropertyName(value: string): string {
  return isIdentifier(value) ? value : JSON.stringify(value);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function getPropertyNameText(property: PropertyAssignment): string | undefined {
  const nameNode = property.getNameNode();

  if (Node.isIdentifier(nameNode) || Node.isNumericLiteral(nameNode)) {
    return nameNode.getText();
  }

  if (
    Node.isStringLiteral(nameNode) ||
    Node.isNoSubstitutionTemplateLiteral(nameNode)
  ) {
    return nameNode.getLiteralText();
  }

  return undefined;
}

function findPropertyAssignment(
  objectLiteral: ObjectLiteralExpression,
  name: string,
): PropertyAssignment | undefined {
  return objectLiteral
    .getProperties()
    .find(
      (property): property is PropertyAssignment =>
        Node.isPropertyAssignment(property) &&
        getPropertyNameText(property) === name,
    );
}

function validateSchemaInitializerExpression(expression: string): void {
  const trimmed = expression.trim();
  if (trimmed.length === 0) {
    throw new Error(
      'schema patch set entries must resolve to a non-empty zod schema expression.',
    );
  }

  const probe = ts.transpileModule(`const value = ${trimmed};`, {
    reportDiagnostics: true,
  });
  const firstError = (probe.diagnostics ?? []).find(
    (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error,
  );

  if (firstError) {
    const message = ts.flattenDiagnosticMessageText(
      firstError.messageText,
      '\n',
    );
    throw new Error(`Invalid zod schema expression "${trimmed}": ${message}`);
  }
}

function resolveSchemaInitializerExpression(schema: z.ZodTypeAny): string {
  const metadata = readZodSchemaExpression(schema);
  if (!metadata) {
    throw new Error(
      'Could not resolve zod schema expression for schema patch set entry. Ensure schema patch entries come from class-based schema properties or explicitly annotated zod schemas.',
    );
  }

  const trimmed = metadata.trim();
  if (trimmed.length === 0) {
    throw new Error(
      'Could not resolve zod schema expression for schema patch set entry. Ensure schema patch entries come from class-based schema properties or explicitly annotated zod schemas.',
    );
  }

  try {
    return extractSchemaExpressionFromMethod(trimmed);
  } catch {
    // Metadata may already be a direct expression (e.g. tests/manual specs).
    return trimmed;
  }
}

function extractSchemaExpressionFromMethod(methodSource: string): string {
  const project = new Project({
    useInMemoryFileSystem: true,
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      newLineKind: NewLineKind.LineFeed,
      quoteKind: QuoteKind.Single,
      useTrailingCommas: true,
    },
  });

  const sourceFile = project.createSourceFile(
    '/SchemaExpressionProbe.ts',
    `class SchemaExpressionProbe { ${methodSource} }`,
    { overwrite: true },
  );

  const classDeclaration = sourceFile.getClassOrThrow('SchemaExpressionProbe');
  const methodDeclaration = classDeclaration.getMethods()[0];
  if (!methodDeclaration) {
    throw new Error('Method declaration not found.');
  }

  const returnStatement = methodDeclaration
    .getStatements()
    .find((statement) => statement.getKind() === SyntaxKind.ReturnStatement);
  if (!returnStatement || !ts.isReturnStatement(returnStatement.compilerNode)) {
    throw new Error('Missing return statement.');
  }

  const expressionNode = returnStatement.compilerNode.expression;
  if (!expressionNode) {
    throw new Error('Method must return an expression.');
  }

  const expression = expressionNode.getText(sourceFile.compilerNode).trim();
  if (expression.length === 0) {
    throw new Error('Returned expression is empty.');
  }

  return expression;
}

function breakInvalidObject(
  payloadPath: string,
  schemaConstName: string,
): never {
  throw new Error(
    `Invalid payloadPath "${payloadPath}". Target must resolve to a z.object(...) shape in schema "${schemaConstName}".`,
  );
}

function breakInvalidArray(
  payloadPath: string,
  schemaConstName: string,
): never {
  throw new Error(
    `Invalid payloadPath "${payloadPath}". Wildcard '*' must resolve to a z.array(...) in schema "${schemaConstName}".`,
  );
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith('\n') ? value : `${value}\n`;
}

function ensureGeneratedTsHeader(sourceText: string): string {
  return sourceText.startsWith(GENERATED_TS_HEADER)
    ? sourceText
    : `${GENERATED_TS_HEADER}${sourceText}`;
}

function evaluateSchemaModuleExport(
  moduleSourceText: string,
  schemaConstName: string,
  version: ApiVersion,
): z.ZodTypeAny {
  const transpile = ts.transpileModule(moduleSourceText, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
    },
    reportDiagnostics: true,
  });

  const firstError = (transpile.diagnostics ?? []).find(
    (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error,
  );
  if (firstError) {
    const message = ts.flattenDiagnosticMessageText(
      firstError.messageText,
      '\n',
    );
    throw new Error(
      `Failed to transpile generated schema module for version ${version}: ${message}`,
    );
  }

  const module = { exports: {} as Record<string, unknown> };
  const localRequire = createRequire(__filename);

  try {
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const executeModule = new Function(
      'require',
      'module',
      'exports',
      transpile.outputText,
    ) as (
      requireFn: NodeJS.Require,
      module: { exports: unknown },
      exports: unknown,
    ) => void;
    executeModule(localRequire, module, module.exports);
  } catch (error) {
    throw new Error(
      `Failed to evaluate generated schema module for version ${version}: ${(error as Error).message}`,
    );
  }

  const exportedSchema = module.exports[schemaConstName];
  if (
    !exportedSchema ||
    typeof exportedSchema !== 'object' ||
    !('safeParse' in exportedSchema) ||
    typeof (exportedSchema as { safeParse?: unknown }).safeParse !== 'function'
  ) {
    throw new Error(
      `Generated schema "${schemaConstName}" for version ${version} did not evaluate to a Zod schema.`,
    );
  }

  return exportedSchema as z.ZodTypeAny;
}
