export const VERSIONING_DEFINITION = Symbol('VERSIONING_DEFINITION');
export const REQUEST_SCHEMAS_BY_VERSION = Symbol('REQUEST_SCHEMAS_BY_VERSION');
export const RESPONSE_SCHEMAS_BY_VERSION = Symbol(
  'RESPONSE_SCHEMAS_BY_VERSION',
);
export const OPENAPI_OPERATION_TARGET = Symbol('OPENAPI_OPERATION_TARGET');
