import { CONFIG } from "../CONFIG.const";

export const FRONT_URLS = [
  CONFIG.SOLIGUIA_AD_URL,
  CONFIG.SOLIGUIA_ES_URL,
  CONFIG.SOLIGUIDE_FR_URL,
];

export const WEBAPP_URLS = [
  CONFIG.WEBAPP_FR_URL,
  CONFIG.WEBAPP_ES_URL,
  CONFIG.WEBAPP_AD_URL,
];

export const SOLIGUIDE_URLS = [...FRONT_URLS, ...WEBAPP_URLS];
