/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  PlaceClosedHolidays,
  PlaceStatus,
  PlaceType,
  PlaceVisibility,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  ServiceSaturation,
} from "@soliguide/common";
import { z } from "zod";

const categoriesEnumSchema = z
  .enum(Categories)
  .meta({ id: "Common_Categories" });
const placeClosedHolidaysEnumSchema = z
  .enum(PlaceClosedHolidays)
  .meta({ id: "Common_PlaceClosedHolidays" });
const placeStatusEnumSchema = z
  .enum(PlaceStatus)
  .describe("Indicate if this place is currently published.")
  .meta({ id: "Common_PlaceStatus", example: PlaceStatus.ONLINE });
const placeTypeEnumSchema = z.enum(PlaceType).meta({ id: "Common_PlaceType" });
const placeVisibilityEnumSchema = z
  .enum(PlaceVisibility)
  .describe("Indicates who has access to information about this place.")
  .meta({ id: "Common_PlaceVisibility", example: "ALL" });
const serviceSaturationEnumSchema = z
  .enum(ServiceSaturation)
  .meta({ id: "Common_ServiceSaturation" });
const publicsAdministrativeEnumSchema = z
  .enum(PublicsAdministrative)
  .meta({ id: "Common_PublicsAdministrative" });
const publicsFamilyEnumSchema = z
  .enum(PublicsFamily)
  .meta({ id: "Common_PublicsFamily" });
const publicsGenderEnumSchema = z
  .enum(PublicsGender)
  .meta({ id: "Common_PublicsGender" });
const publicsOtherEnumSchema = z
  .enum(PublicsOther)
  .meta({ id: "Common_PublicsOther" });

const dateSchema = z
  .string()
  .describe("Date-time value. Format ISO 8601.")
  .meta({ id: "SearchResponse_Date" });

const positionSchema = z
  .looseObject({
    location: z
      .object({
        type: z
          .literal("Point")
          .nullable()
          .optional()
          .describe("Geographic object type. Always `Point`."),
        coordinates: z
          .array(z.number())
          .nullable()
          .optional()
          .describe(
            "Geographic coordinates of the place as `[longitude, latitude]`. Format GeoJSON.."
          ),
      })
      .nullable()
      .optional()
      .describe("Geographic location of the place."),
    address: z
      .string()
      .nullable()
      .optional()
      .describe("Street address of the place."),
    additionalInformation: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Additional address information such as building, floor or access details."
      ),
    city: z.string().nullable().optional().describe("City name of the place."),
    cityCode: z
      .string()
      .nullable()
      .optional()
      .describe("Administrative code of the city."),
    postalCode: z
      .string()
      .nullable()
      .optional()
      .describe("Postal code of the place."),
    department: z
      .string()
      .nullable()
      .optional()
      .describe("Department name of the place."),
    departmentCode: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Department code of the place. Examples: `974`, `2A`, `91`, `06`."
      ),
    region: z
      .string()
      .nullable()
      .optional()
      .describe("Region name of the place."),
    regionCode: z
      .string()
      .nullable()
      .optional()
      .describe("Administrative code of the region."),
    slugs: z
      .looseObject({
        city: z.string().nullable().optional(),
        country: z.string().nullable().optional(),
        department: z.string().nullable().optional(),
        region: z.string().nullable().optional(),
        ville: z.string().nullable().optional(),
      })
      .nullable()
      .optional()
      .describe("URL compatible labels for position's text properties"),
    country: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Country code of the place. Format ISO 3166-1 alpha-2. Lower case"
      ),
    timeZone: z
      .string()
      .nullable()
      .optional()
      .describe("Time zone of the place. Format IANA time zone identifier."),
  })
  .meta({ id: "SearchResponse_Position" });

const photoSchema = z
  .looseObject({
    _id: z.string().nullable().optional(),
    encoding: z.string().nullable().optional(),
    filename: z.string().nullable(),
    mimetype: z.string().nullable(),
    parcours_id: z.number().int().nullable().optional(),
    path: z.string().nullable(),
    lieu_id: z.number().int().nullable(),
    size: z.number().nullable().optional(),
    createdAt: dateSchema.nullable().optional(),
    updatedAt: dateSchema.nullable().optional(),
  })
  .meta({ id: "SearchResponse_Photo" });

const timeslotSchema = z
  .looseObject({
    start: z
      .number()
      .nullable()
      .optional()
      .describe(
        "Start time of the opening slot, encoded as `HHmm` without separator, using 3 or 4 digits."
      ),
    end: z
      .number()
      .nullable()
      .optional()
      .describe(
        "End time of the opening slot, encoded as `HHmm` without separator, using 3 or 4 digits."
      ),
  })
  .meta({ id: "SearchResponse_Timeslot" });

const dayOpeningHoursSchema = z
  .looseObject({
    open: z
      .boolean()
      .nullable()
      .optional()
      .describe("Indicates whether the place or service is open on that day."),
    timeslot: z
      .array(timeslotSchema)
      .nullable()
      .optional()
      .describe("Opening slots for the day. Up to 3 slots can be defined."),
  })
  .meta({ id: "SearchResponse_DayOpeningHours" });

const openingHoursSchema = z
  .looseObject({
    closedHolidays: placeClosedHolidaysEnumSchema
      .nullable()
      .optional()
      .describe(
        "Opening behavior on public holidays: `UNKNOWN` when not specified, `OPEN` when open, `CLOSED` when closed."
      ),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Free-text details about opening hours."),
    monday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Monday."),
    tuesday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Tuesday."),
    wednesday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Wednesday."),
    thursday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Thursday."),
    friday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Friday."),
    saturday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Saturday."),
    sunday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Sunday."),
  })
  .meta({ id: "SearchResponse_OpeningHours" });

const modalitiesCheckSchema = z
  .looseObject({
    checked: z
      .boolean()
      .nullable()
      .optional()
      .describe("Indicates whether the access condition applies."),
    precisions: z
      .string()
      .nullable()
      .optional()
      .describe("Additional details about the access condition."),
  })
  .meta({ id: "SearchResponse_ModalitiesCheck" });

const modalitiesSchema = z
  .looseObject({
    unconditional: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates unconditional access. When `true`, it is the only access condition to consider."
      ),
    appointment: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Access by appointment."),
    registration: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Access requiring prior registration."),
    referral: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe(
        "Access requiring orientation. When this condition applies, address and coordinates must not be displayed publicly unless explicitly allowed by agreement."
      ),
    price: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Indicates the service is fee-based."),
    animals: z
      .object({
        checked: z
          .boolean()
          .nullable()
          .optional()
          .describe("Indicates whether animals are accepted."),
      })
      .nullable()
      .optional()
      .describe("Animal access policy."),
    accessibility: z
      .object({
        wheelchair: z
          .boolean()
          .nullable()
          .optional()
          .describe(
            "Indicates whether the place is accessible to wheelchair users."
          ),
      })
      .nullable()
      .optional()
      .describe("Accessibility details for the place."),
    docs: z.array(z.string()).nullable().optional(),
    other: z
      .string()
      .nullable()
      .optional()
      .describe("Additional details about access conditions."),
  })
  .meta({ id: "SearchResponse_Modalities" });

const publicsSchema = z
  .looseObject({
    welcomeType: z
      .union([z.literal(0), z.literal(1), z.literal(2)])
      .nullable()
      .optional()
      .describe(
        "Type of welcome for the public: `0` unconditional, `1` unconditional adapted to a specific public, `2` exclusive."
      ),
    administrative: z
      .array(publicsAdministrativeEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Administrative statuses accepted by the place. If every possible value is selected, it means there is no restriction."
      ),
    age: z
      .object({
        min: z.number().nullable().optional().describe("Minimum accepted age."),
        max: z
          .number()
          .nullable()
          .optional()
          .describe("Maximum accepted age. "),
      })
      .nullable()
      .optional()
      .describe(
        "Age restrictions for the accepted public. Values from `0` to `99` mean no age restriction."
      ),
    description: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Free-text details about specific public restrictions or adaptations."
      ),
    family: z
      .array(publicsFamilyEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Family situations accepted by the place. If every possible value is selected, it means there is no restriction."
      ),
    gender: z
      .array(publicsGenderEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Gender-related restrictions or adaptations. If every possible value is selected, it means there is no restriction."
      ),
    other: z
      .array(publicsOtherEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Other audience restrictions or adaptations. If every possible value is selected, it means there is no restriction."
      ),
    specialSupportContext: z
      .object({
        type: z.string().describe("Broad category of support context.").meta({
          example: "humanitarianCrisis",
        }),
        key: z
          .string()
          .describe(
            "Stable machine-readable identifier for the support context."
          )
          .meta({
            example: "ukraine-displacement",
          }),
        label: z
          .string()
          .describe("Human-readable label for the support context.")
          .meta({
            example: "Support for displaced people from Ukraine",
          }),
        details: z
          .string()
          .describe(
            "Additional details about the support available in this context."
          )
          .meta({
            example: "Ukrainian-speaking volunteers available.",
          }),
      })
      .nullable()
      .optional()
      .describe(
        "Special support context related to a crisis or exceptional situation."
      ),
  })
  .meta({ id: "SearchResponse_Publics" });

const categorySpecificFieldsSchema = z
  .looseObject({
    activityName: z.string().nullable().optional(),
    availableEquipmentPrecisions: z.string().nullable().optional(),
    availableEquipmentType: z.array(z.string()).nullable().optional(),
    babyParcelAgeType: z.array(z.string()).nullable().optional(),
    canteensMealType: z.string().nullable().optional(),
    courseType: z.string().nullable().optional(),
    degreeOfChoiceType: z.string().nullable().optional(),
    dietaryAdaptationsType: z.array(z.string()).nullable().optional(),
    dietaryRegimesType: z.string().nullable().optional(),
    domiciliationType: z.string().nullable().optional(),
    foodProductType: z.array(z.string()).nullable().optional(),
    otherProductTypePrecisions: z.string().nullable().optional(),
    hygieneProductType: z.string().nullable().optional(),
    jobsList: z.string().nullable().optional(),
    nationalOriginProductType: z.string().nullable().optional(),
    organicOriginProductType: z.string().nullable().optional(),
    serviceStyleType: z.array(z.string()).nullable().optional(),
    usageModality: z.string().nullable().optional(),
    voucherType: z.string().nullable().optional(),
    voucherTypePrecisions: z.string().nullable().optional(),
    wellnessActivityName: z.string().nullable().optional(),
  })
  .describe(
    "Category-specific service details. Available fields depend on the service category."
  )
  .meta({ id: "SearchResponse_CategorySpecificFields" });

const serviceSchema = z
  .looseObject({
    category: categoriesEnumSchema
      .nullable()
      .describe("Category of the service."),
    tempClosure: z
      .object({
        active: z.boolean().nullable().optional(),
        startDate: dateSchema.nullable().optional(),
        endDate: dateSchema.nullable().optional(),
        precision: z.string().nullable().optional(),
        closeType: z.number().nullable().optional(),
      })
      .nullable()
      .optional()
      .describe("Temporary closure settings for the service."),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Localized HTML content describing the service."),
    differentHours: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service has opening hours different from the place."
      ),
    differentModalities: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service has access conditions different from the place."
      ),
    differentPublics: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service welcomes a public different from the place."
      ),
    hours: openingHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours specific to the service."),
    isOpenToday: z
      .boolean()
      .nullable()
      .describe("Whether the service is open today. Recalculated daily."),
    modalities: modalitiesSchema
      .nullable()
      .optional()
      .describe("Access conditions specific to the service."),
    publics: publicsSchema
      .nullable()
      .optional()
      .describe("Audience information specific to the service."),
    saturated: z
      .object({
        precision: z.string().nullable().optional(),
        status: serviceSaturationEnumSchema.nullable().optional(),
      })
      .nullable()
      .optional()
      .describe("Current saturation status of the service."),
    serviceObjectId: z
      .string()
      .nullable()
      .describe("Internal identifier of the service."),
    createdAt: dateSchema
      .nullable()
      .describe("Creation date of the service. Format ISO 8601."),
    categorySpecificFields: categorySpecificFieldsSchema
      .nullable()
      .optional()
      .describe("Details specific to the service category."),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Deprecated additional label for some service categories.")
      .meta({ deprecated: true }),
  })
  .meta({ id: "SearchResponse_Service" });
const sourceSchema = z
  .looseObject({
    ids: z
      .array(
        z.looseObject({
          id: z
            .string()
            .nullable()
            .describe(
              "Formatted external identifier of the source. Format UUID."
            ),
          url: z
            .string()
            .nullable()
            .optional()
            .describe("Source URL when available."),
        })
      )
      .nullable()
      .optional()
      .describe(
        "Various sources of information providing data about this place."
      ),
    isOrigin: z
      .boolean()
      .nullable()
      .describe("Indicates if the place has been created by the source."),
    license: z
      .string()
      .nullable()
      .optional()
      .describe("URL of the license associated to the data."),
    name: z.string().nullable().describe("Name of the source"),
  })
  .meta({ id: "SearchResponse_Source" });

const parcoursSchema = z
  .looseObject({
    description: z.string().nullable().optional(),
    hours: openingHoursSchema.nullable().optional(),
    position: positionSchema.nullable().optional(),
    photos: z.array(photoSchema).nullable().optional(),
    show: z.boolean().nullable().optional(),
  })
  .meta({ id: "SearchResponse_Parcours" });

const phoneSchema = z
  .looseObject({
    label: z
      .string()
      .nullable()
      .optional()
      .describe("Label describing the phone contact."),
    phoneNumber: z
      .string()
      .nullable()
      .optional()
      .describe("Phone number of the contact."),
    countryCode: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Country code used to interpret the phone number. Format ISO 3166-1 alpha-2."
      ),
    isSpecialPhoneNumber: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the phone number is a special short number."
      ),
  })
  .meta({ id: "SearchResponse_Phone" });

const entitySchema = z
  .looseObject({
    facebook: z
      .string()
      .nullable()
      .optional()
      .describe("Facebook page URL of the organization."),
    fax: z
      .string()
      .nullable()
      .optional()
      .describe("Fax number of the organization."),
    instagram: z
      .string()
      .nullable()
      .optional()
      .describe("Instagram page URL of the organization."),
    mail: z
      .string()
      .nullable()
      .optional()
      .describe("Email address of the organization."),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Name of the organization."),
    phones: z
      .array(phoneSchema)
      .nullable()
      .optional()
      .describe("Phone contacts of the organization."),
    website: z
      .string()
      .nullable()
      .optional()
      .describe("Website URL of the organization."),
  })
  .meta({ id: "SearchResponse_Entity" });

const slugsSchema = z
  .looseObject({
    infos: z
      .object({
        description: z.string().nullable().optional(),
        name: z.string().nullable().optional(),
      })
      .nullable()
      .optional(),
  })
  .meta({ id: "SearchResponse_Slugs" });

const v20260426SearchPlaceResponseSchema = z
  .object({
    lieu_id: z
      .int()
      .nullable()
      .optional()
      .describe("Numeric place identifier."),
    _id: z
      .string()
      .nullable()
      .optional()
      .describe("Internal identifier of the place"),
    seoUrl: z
      .string()
      .nullable()
      .optional()
      .describe("SEO-friendly URL slug of the place."),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Localized name of the place."),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Localized HTML content describing the place."),
    status: placeStatusEnumSchema
      .nullable()
      .optional()
      .describe(
        "Publication status of the place: `DRAFT`, `ONLINE`, `OFFLINE` or `CLOSED`."
      ),
    visibility: placeVisibilityEnumSchema
      .nullable()
      .optional()
      .describe("Indicates who can access information about this place."),
    isOpenToday: z
      .boolean()
      .nullable()
      .optional()
      .describe("Whether the place is open today. Recalculated daily."),
    photos: z.array(photoSchema).nullable().optional(),
    placeType: placeTypeEnumSchema.nullable().optional(),
    services: z
      .array(serviceSchema)
      .nullable()
      .optional()
      .describe("List of services available at the place."),
    position: positionSchema
      .nullable()
      .optional()
      .describe("Address and geographic information of the place."),
    waypoints: z
      .array(parcoursSchema)
      .nullable()
      .optional()
      .describe(
        'Details about the Parcours of a facility when `placeType` is "PARCOURS_MOBILE"'
      ),
    organizationInfo: entitySchema
      .nullable()
      .optional()
      .describe("Organization contact information."),
    openingHours: openingHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours of the place."),
    modalities: modalitiesSchema
      .nullable()
      .optional()
      .describe("Access conditions of the place."),
    publics: publicsSchema
      .nullable()
      .optional()
      .describe("Audience welcomed at the place."),
    country: z
      .string()
      .nullable()
      .optional()
      .describe("Country code of the place. Format ISO 3166-1 alpha-2."),
    languages: z
      .array(z.string())
      .nullable()
      .optional()
      .describe("Languages spoken at the place. Format ISO 639-3."),
    createdAt: dateSchema
      .nullable()
      .optional()
      .describe("Creation date of the place. Format ISO 8601."),
    updatedAt: dateSchema
      .nullable()
      .optional()
      .describe("Last update date of the place. Format ISO 8601."),
    updatedByUserAt: dateSchema
      .nullable()
      .optional()
      .describe("Last user update date of the place. Format ISO 8601."),
    tempInfo: z
      .looseObject({
        closure: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
          })
          .nullable()
          .optional()
          .describe("Temporary closure of the place."),
        hours: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
            hours: z
              .looseObject({})
              .nullable()
              .optional()
              .describe("Temporary opening hours of the place."),
          })
          .nullable()
          .optional()
          .describe("Temporary opening hours of the place."),
        message: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
            name: z.string().nullable().optional(),
          })
          .nullable()
          .optional(),
      })
      .nullable()
      .optional()
      .describe("Temporary closure, opening hours and message information."),
    sources: z
      .array(sourceSchema)
      .nullable()
      .optional()
      .describe("External data sources paired with the place."),
    slugs: slugsSchema.nullable().optional(),
    distance: z
      .number()
      .nullable()
      .optional()
      .describe("Distance between the search center and the place, in meters."),
  })
  .meta({
    id: "v20260426SearchPlaceResponse",
  });

export const v20260426SearchResponseSchema = z
  .object({
    nbResults: z
      .number()
      .int()
      .min(0)
      .nullable()
      .describe("Total number of places matching the request."),
    places: z.array(
      z
        .discriminatedUnion("placeType", [
          v20260426SearchPlaceResponseSchema
            .omit({ waypoints: true })
            .extend({
              placeType: z.literal(PlaceType.PLACE),
            })
            .meta({ title: "FixedPosition" }),
          v20260426SearchPlaceResponseSchema
            .omit({ openingHours: true, position: true })
            .extend({
              placeType: z.literal(PlaceType.ITINERARY),
            })
            .meta({ title: "Itinerary" }),
        ])
        .meta({
          discriminator: {
            propertyName: "type",
          },
        })
        .nullable()
        .describe("List of place matching the request.")
    ),
  })
  .meta({ id: "v20260426SearchResponse" });

export type V20260426SearchResponse = z.infer<
  typeof v20260426SearchResponseSchema
>;

export default v20260426SearchResponseSchema;
