/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import {
  Categories,
  CountryCodes,
  PLACE_LANGUAGES_LIST_MAP_KEY,
  PlaceClosedHolidays,
  PlaceStatus,
  PlaceType,
  PlaceVisibility,
  PublicsAdministrative,
  PublicsFamily,
  PublicsGender,
  PublicsOther,
  ServiceSaturation,
} from "@soliguide/common";
import { z } from "zod";

const categoriesEnumSchema = z
  .enum(Categories)
  .meta({ id: "Common_Categories" });
const countryCodesEnumSchema = z
  .enum([CountryCodes.FR, CountryCodes.ES, CountryCodes.AD])
  .describe(
    "Country code restricted to Soliguide countries. Format ISO 3166-1 alpha-2."
  )
  .meta({ id: "Common_SoliguideCountries" });
const placeLanguagesEnumSchema = z
  .enum(PLACE_LANGUAGES_LIST_MAP_KEY)
  .describe("Language code spoken at the place.")
  .meta({ id: "Common_PlaceLanguages" });
const placeClosedHolidaysEnumSchema = z
  .enum(PlaceClosedHolidays)
  .meta({ id: "Common_PlaceClosedHolidays" });
const placeStatusEnumSchema = z
  .enum(PlaceStatus)
  .describe("Indicate if this place is currently published.")
  .meta({ id: "Common_PlaceStatus", example: PlaceStatus.ONLINE });
const placeTypeEnumSchema = z.enum(PlaceType).meta({ id: "Common_PlaceType" });
const placeVisibilityEnumSchema = z
  .enum(PlaceVisibility)
  .describe("Indicates who has access to information about this place.")
  .meta({ id: "Common_PlaceVisibility", example: "ALL" });
const serviceSaturationEnumSchema = z
  .enum(ServiceSaturation)
  .meta({ id: "Common_ServiceSaturation" });
const publicsAdministrativeEnumSchema = z
  .enum(PublicsAdministrative)
  .meta({ id: "Common_PublicsAdministrative" });
const publicsFamilyEnumSchema = z
  .enum(PublicsFamily)
  .meta({ id: "Common_PublicsFamily" });
const publicsGenderEnumSchema = z
  .enum(PublicsGender)
  .meta({ id: "Common_PublicsGender" });
const publicsOtherEnumSchema = z
  .enum(PublicsOther)
  .meta({ id: "Common_PublicsOther" });

const dateSchema = z
  .string()
  .describe("Date-time value. Format ISO 8601.")
  .meta({
    id: "SearchResponse_Date",
    example: "2026-04-26T00:00:00.000Z",
  });

const positionSchema = z
  .looseObject({
    location: z
      .object({
        type: z
          .literal("Point")
          .nullable()
          .optional()
          .describe("Geographic object type. Always `Point`.")
          .meta({ example: "Point" }),
        coordinates: z
          .array(z.number())
          .nullable()
          .optional()
          .describe(
            "Geographic coordinates of the place as `[longitude, latitude]`. Format GeoJSON.."
          )
          .meta({ example: [2.3522, 48.8566] }),
      })
      .nullable()
      .optional()
      .describe("Geographic location of the place."),
    address: z
      .string()
      .nullable()
      .optional()
      .describe("Street address of the place.")
      .meta({ example: "12 rue du Faubourg Saint-Antoine" }),
    additionalInformation: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Additional address information such as building, floor or access details."
      )
      .meta({ example: "Bâtiment B, 2e étage" }),
    city: z
      .string()
      .nullable()
      .optional()
      .describe("City name of the place.")
      .meta({ example: "Paris" }),
    cityCode: z
      .string()
      .nullable()
      .optional()
      .describe("Administrative code of the city.")
      .meta({ example: "75056" }),
    postalCode: z
      .string()
      .nullable()
      .optional()
      .describe("Postal code of the place.")
      .meta({ example: "75013" }),
    department: z
      .string()
      .nullable()
      .optional()
      .describe("Department name of the place.")
      .meta({ example: "Paris" }),
    departmentCode: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Department code of the place. Examples: `974`, `2A`, `91`, `06`."
      )
      .meta({ example: "75" }),
    region: z
      .string()
      .nullable()
      .optional()
      .describe("Region name of the place.")
      .meta({ example: "Île-de-France" }),
    regionCode: z
      .string()
      .nullable()
      .optional()
      .describe("Administrative code of the region.")
      .meta({ example: "11" }),
    slugs: z
      .looseObject({
        city: z.string().nullable().optional().meta({ example: "paris-75013" }),
        country: z.string().nullable().optional().meta({ example: "france" }),
        department: z.string().nullable().optional().meta({ example: "paris" }),
        region: z
          .string()
          .nullable()
          .optional()
          .meta({ example: "ile-de-france" }),
        ville: z
          .string()
          .nullable()
          .optional()
          .meta({ example: "paris-75013" }),
      })
      .nullable()
      .optional()
      .describe("URL compatible labels for position's text properties"),
    country: countryCodesEnumSchema
      .nullable()
      .optional()
      .describe("Country code of the place.")
      .meta({ example: CountryCodes.FR }),
    timeZone: z
      .string()
      .nullable()
      .optional()
      .describe("Time zone of the place. Format IANA time zone identifier.")
      .meta({ example: "Europe/Paris" }),
  })
  .meta({ id: "SearchResponse_Position" });

const photoSchema = z
  .looseObject({
    _id: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "5a58c0c7c1797fe45e377335" }),
    encoding: z.string().nullable().optional().meta({ example: "7bit" }),
    filename: z.string().nullable().meta({ example: "photo-1.jpg" }),
    mimetype: z.string().nullable().meta({ example: "image/jpeg" }),
    parcours_id: z.number().int().nullable().optional(),
    path: z
      .string()
      .nullable()
      .meta({ example: "https://cdn.soliguide.fr/photos/169/photo-1.jpg" }),
    lieu_id: z.number().int().nullable().meta({ example: 169 }),
    size: z.number().nullable().optional().meta({ example: 145823 }),
    createdAt: dateSchema.nullable().optional(),
    updatedAt: dateSchema.nullable().optional(),
  })
  .meta({ id: "SearchResponse_Photo" });

const timeslotSchema = z
  .looseObject({
    start: z
      .number()
      .nullable()
      .optional()
      .describe(
        "Start time of the opening slot, encoded as `HHmm` without separator, using 3 or 4 digits."
      )
      .meta({ example: 900 }),
    end: z
      .number()
      .nullable()
      .optional()
      .describe(
        "End time of the opening slot, encoded as `HHmm` without separator, using 3 or 4 digits."
      )
      .meta({ example: 1230 }),
  })
  .meta({ id: "SearchResponse_Timeslot" });

const dayOpeningHoursSchema = z
  .looseObject({
    open: z
      .boolean()
      .nullable()
      .optional()
      .describe("Indicates whether the place or service is open on that day.")
      .meta({ example: true }),
    timeslot: z
      .array(timeslotSchema)
      .nullable()
      .optional()
      .describe("Opening slots for the day. Up to 3 slots can be defined."),
  })
  .meta({ id: "SearchResponse_DayOpeningHours" });

const openingHoursSchema = z
  .looseObject({
    closedHolidays: placeClosedHolidaysEnumSchema
      .nullable()
      .optional()
      .describe(
        "Opening behavior on public holidays: `UNKNOWN` when not specified, `OPEN` when open, `CLOSED` when closed."
      )
      .meta({ example: PlaceClosedHolidays.UNKNOWN }),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Free-text details about opening hours.")
      .meta({ example: "Ouvert du lundi au vendredi." }),
    monday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Monday."),
    tuesday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Tuesday."),
    wednesday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Wednesday."),
    thursday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Thursday."),
    friday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Friday."),
    saturday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Saturday."),
    sunday: dayOpeningHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours for Sunday."),
  })
  .meta({ id: "SearchResponse_OpeningHours" });

const modalitiesCheckSchema = z
  .looseObject({
    checked: z
      .boolean()
      .nullable()
      .optional()
      .describe("Indicates whether the access condition applies.")
      .meta({ example: true }),
    precisions: z
      .string()
      .nullable()
      .optional()
      .describe("Additional details about the access condition.")
      .meta({ example: "Sur orientation d'un travailleur social." }),
  })
  .meta({ id: "SearchResponse_ModalitiesCheck" });

const modalitiesSchema = z
  .looseObject({
    unconditional: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates unconditional access. When `true`, it is the only access condition to consider."
      )
      .meta({ example: true }),
    appointment: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Access by appointment."),
    registration: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Access requiring prior registration."),
    referral: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe(
        "Access requiring orientation. When this condition applies, address and coordinates must not be displayed publicly unless explicitly allowed by agreement."
      ),
    price: modalitiesCheckSchema
      .nullable()
      .optional()
      .describe("Indicates the service is fee-based."),
    animals: z
      .object({
        checked: z
          .boolean()
          .nullable()
          .optional()
          .describe("Indicates whether animals are accepted.")
          .meta({ example: false }),
      })
      .nullable()
      .optional()
      .describe("Animal access policy."),
    accessibility: z
      .object({
        wheelchair: z
          .boolean()
          .nullable()
          .optional()
          .describe(
            "Indicates whether the place is accessible to wheelchair users."
          ),
      })
      .nullable()
      .optional()
      .describe("Accessibility details for the place."),
    docs: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["pieceIdentite", "justificatifDomicile"] }),
    other: z
      .string()
      .nullable()
      .optional()
      .describe("Additional details about access conditions.")
      .meta({ example: "Prévoir une pièce d'identité." }),
  })
  .meta({ id: "SearchResponse_Modalities" });

const publicsSchema = z
  .looseObject({
    welcomeType: z
      .union([z.literal(0), z.literal(1), z.literal(2)])
      .nullable()
      .optional()
      .describe(
        "Type of welcome for the public: `0` unconditional, `1` unconditional adapted to a specific public, `2` exclusive."
      )
      .meta({ example: 0 }),
    administrative: z
      .array(publicsAdministrativeEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Administrative statuses accepted by the place. If every possible value is selected, it means there is no restriction."
      )
      .meta({ example: ["regular", "asylum", "refugee"] }),
    age: z
      .object({
        min: z
          .number()
          .nullable()
          .optional()
          .describe("Minimum accepted age.")
          .meta({ example: 0 }),
        max: z
          .number()
          .nullable()
          .optional()
          .describe("Maximum accepted age. ")
          .meta({ example: 99 }),
      })
      .nullable()
      .optional()
      .describe(
        "Age restrictions for the accepted public. Values from `0` to `99` mean no age restriction."
      ),
    description: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Free-text details about specific public restrictions or adaptations."
      )
      .meta({ example: "Public en situation de grande précarité." }),
    family: z
      .array(publicsFamilyEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Family situations accepted by the place. If every possible value is selected, it means there is no restriction."
      )
      .meta({ example: ["isolated", "family"] }),
    gender: z
      .array(publicsGenderEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Gender-related restrictions or adaptations. If every possible value is selected, it means there is no restriction."
      )
      .meta({ example: ["men", "women"] }),
    other: z
      .array(publicsOtherEnumSchema)
      .nullable()
      .optional()
      .describe(
        "Other audience restrictions or adaptations. If every possible value is selected, it means there is no restriction."
      )
      .meta({ example: [] }),
    specialSupportContext: z
      .object({
        type: z.string().describe("Broad category of support context.").meta({
          example: "humanitarianCrisis",
        }),
        key: z
          .string()
          .describe(
            "Stable machine-readable identifier for the support context."
          )
          .meta({
            example: "ukraine-displacement",
          }),
        label: z
          .string()
          .describe("Human-readable label for the support context.")
          .meta({
            example: "Support for displaced people from Ukraine",
          }),
        details: z
          .string()
          .describe(
            "Additional details about the support available in this context."
          )
          .meta({
            example: "Ukrainian-speaking volunteers available.",
          }),
      })
      .nullable()
      .optional()
      .describe(
        "Special support context related to a crisis or exceptional situation."
      ),
  })
  .meta({ id: "SearchResponse_Publics" });

const categorySpecificFieldsSchema = z
  .looseObject({
    activityName: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "Atelier théâtre" }),
    availableEquipmentPrecisions: z.string().nullable().optional(),
    availableEquipmentType: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["oven", "microwaves"] }),
    babyParcelAgeType: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["under_six_months"] }),
    canteensMealType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "dejeuner" }),
    courseType: z.string().nullable().optional().meta({ example: "fle" }),
    degreeOfChoiceType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "free_choice" }),
    dietaryAdaptationsType: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["vegetarian", "halal"] }),
    dietaryRegimesType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "we_adapt" }),
    domiciliationType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "domi1" }),
    foodProductType: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["fresh_produce", "non_perishable"] }),
    otherProductTypePrecisions: z.string().nullable().optional(),
    hygieneProductType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "sanitary_materials" }),
    jobsList: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "Manutention, Restauration" }),
    nationalOriginProductType: z.string().nullable().optional(),
    organicOriginProductType: z.string().nullable().optional(),
    serviceStyleType: z
      .array(z.string())
      .nullable()
      .optional()
      .meta({ example: ["indoor_seating", "take_away"] }),
    usageModality: z.string().nullable().optional(),
    voucherType: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "food_voucher" }),
    voucherTypePrecisions: z.string().nullable().optional(),
    wellnessActivityName: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "Massage du dos" }),
  })
  .describe(
    "Category-specific service details. Available fields depend on the service category."
  )
  .meta({ id: "SearchResponse_CategorySpecificFields" });

const serviceSchema = z
  .looseObject({
    category: categoriesEnumSchema
      .nullable()
      .describe("Category of the service.")
      .meta({ example: "food" }),
    tempClosure: z
      .object({
        active: z.boolean().nullable().optional().meta({ example: false }),
        startDate: dateSchema.nullable().optional(),
        endDate: dateSchema.nullable().optional(),
        precision: z
          .string()
          .nullable()
          .optional()
          .meta({ example: "Suspendu jusqu'à la rentrée." }),
        closeType: z.number().nullable().optional().meta({ example: 1 }),
      })
      .nullable()
      .optional()
      .describe("Temporary closure settings for the service."),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Localized HTML content describing the service.")
      .meta({
        example: "<p>Distribution de repas chauds tous les soirs.</p>",
      }),
    differentHours: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service has opening hours different from the place."
      )
      .meta({ example: false }),
    differentModalities: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service has access conditions different from the place."
      )
      .meta({ example: false }),
    differentPublics: z
      .boolean()
      .nullable()
      .optional()
      .describe(
        "Indicates whether the service welcomes a public different from the place."
      )
      .meta({ example: false }),
    hours: openingHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours specific to the service."),
    isOpenToday: z
      .boolean()
      .nullable()
      .describe("Whether the service is open today. Recalculated daily.")
      .meta({ example: true }),
    modalities: modalitiesSchema
      .nullable()
      .optional()
      .describe("Access conditions specific to the service."),
    publics: publicsSchema
      .nullable()
      .optional()
      .describe("Audience information specific to the service."),
    saturated: z
      .object({
        precision: z.string().nullable().optional(),
        status: serviceSaturationEnumSchema.nullable().optional(),
      })
      .nullable()
      .optional()
      .describe("Current saturation status of the service."),
    serviceObjectId: z
      .string()
      .nullable()
      .describe("Internal identifier of the service.")
      .meta({ example: "5a58c0c7c1797fe45e377334" }),
    createdAt: dateSchema
      .nullable()
      .describe("Creation date of the service. Format ISO 8601."),
    categorySpecificFields: categorySpecificFieldsSchema
      .nullable()
      .optional()
      .describe("Details specific to the service category."),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Deprecated additional label for some service categories.")
      .meta({ deprecated: true }),
  })
  .meta({ id: "SearchResponse_Service" });
const sourceSchema = z
  .looseObject({
    ids: z
      .array(
        z.looseObject({
          id: z
            .string()
            .nullable()
            .describe(
              "Formatted external identifier of the source. Format UUID."
            )
            .meta({ example: "9c3f1a2b-4d5e-6789-abcd-ef0123456789" }),
          url: z
            .string()
            .nullable()
            .optional()
            .describe("Source URL when available.")
            .meta({
              example: "https://data.gouv.fr/datasets/restos-du-coeur",
            }),
        })
      )
      .nullable()
      .optional()
      .describe(
        "Various sources of information providing data about this place."
      ),
    isOrigin: z
      .boolean()
      .nullable()
      .describe("Indicates if the place has been created by the source.")
      .meta({ example: true }),
    license: z
      .string()
      .nullable()
      .optional()
      .describe("URL of the license associated to the data.")
      .meta({ example: "https://opendatacommons.org/licenses/odbl/1-0/" }),
    name: z
      .string()
      .nullable()
      .describe("Name of the source")
      .meta({ example: "Soliguide" }),
  })
  .meta({ id: "SearchResponse_Source" });

const parcoursSchema = z
  .looseObject({
    description: z
      .string()
      .nullable()
      .optional()
      .meta({ example: "Étape de l'itinérance hebdomadaire." }),
    hours: openingHoursSchema.nullable().optional(),
    position: positionSchema.nullable().optional(),
    photos: z.array(photoSchema).nullable().optional(),
    show: z.boolean().nullable().optional().meta({ example: true }),
  })
  .meta({ id: "SearchResponse_Parcours" });

const phoneSchema = z
  .looseObject({
    label: z
      .string()
      .nullable()
      .optional()
      .describe("Label describing the phone contact.")
      .meta({ example: "Standard" }),
    phoneNumber: z
      .string()
      .nullable()
      .optional()
      .describe("Phone number of the contact.")
      .meta({ example: "+33 1 53 32 23 23" }),
    countryCode: z
      .string()
      .nullable()
      .optional()
      .describe(
        "Country code used to interpret the phone number. Format ISO 3166-1 alpha-2."
      )
      .meta({ example: "fr" }),
    isSpecialPhoneNumber: z
      .boolean()
      .nullable()
      .optional()
      .describe("Indicates whether the phone number is a special short number.")
      .meta({ example: false }),
  })
  .meta({ id: "SearchResponse_Phone" });

const entitySchema = z
  .looseObject({
    facebook: z
      .string()
      .nullable()
      .optional()
      .describe("Facebook page URL of the organization.")
      .meta({ example: "https://www.facebook.com/restosducoeur" }),
    fax: z
      .string()
      .nullable()
      .optional()
      .describe("Fax number of the organization."),
    instagram: z
      .string()
      .nullable()
      .optional()
      .describe("Instagram page URL of the organization.")
      .meta({ example: "https://www.instagram.com/restosducoeur" }),
    mail: z
      .string()
      .nullable()
      .optional()
      .describe("Email address of the organization.")
      .meta({ example: "contact@restosducoeur.org" }),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Name of the organization.")
      .meta({ example: "Les Restos du Coeur" }),
    phones: z
      .array(phoneSchema)
      .nullable()
      .optional()
      .describe("Phone contacts of the organization."),
    website: z
      .string()
      .nullable()
      .optional()
      .describe("Website URL of the organization.")
      .meta({ example: "https://www.restosducoeur.org" }),
  })
  .meta({ id: "SearchResponse_Entity" });

const slugsSchema = z
  .looseObject({
    infos: z
      .object({
        description: z
          .string()
          .nullable()
          .optional()
          .meta({ example: "distribution-repas-chauds-soir" }),
        name: z.string().nullable().optional().meta({
          example: "camions-des-restos-du-coeur-salpetriere-paris-169",
        }),
      })
      .nullable()
      .optional(),
  })
  .meta({ id: "SearchResponse_Slugs" });

const v20260426SearchPlaceResponseSchema = z
  .object({
    lieu_id: z
      .int()
      .nullable()
      .optional()
      .describe("Numeric place identifier.")
      .meta({ example: 169 }),
    _id: z
      .string()
      .nullable()
      .optional()
      .describe("Internal identifier of the place")
      .meta({ example: "5a58c0c7c1797fe45e377333" }),
    seoUrl: z
      .string()
      .nullable()
      .optional()
      .describe("SEO-friendly URL slug of the place.")
      .meta({
        example: "camions-des-restos-du-coeur-salpetriere-paris-169",
      }),
    name: z
      .string()
      .nullable()
      .optional()
      .describe("Localized name of the place.")
      .meta({ example: "Restos du Coeur - Camion de Paris 5e" }),
    description: z
      .string()
      .nullable()
      .optional()
      .describe("Localized HTML content describing the place.")
      .meta({
        example:
          "<p>Les équipes des Restos du Coeur se rendent sur des points fixes pour partager des moments de rencontre et de convivialité autour d'un repas à consommer sur place.</p>",
      }),
    status: placeStatusEnumSchema
      .nullable()
      .optional()
      .describe(
        "Publication status of the place: `DRAFT`, `ONLINE`, `OFFLINE` or `CLOSED`."
      )
      .meta({ example: PlaceStatus.ONLINE }),
    visibility: placeVisibilityEnumSchema
      .nullable()
      .optional()
      .describe("Indicates who can access information about this place.")
      .meta({ example: PlaceVisibility.ALL }),
    isOpenToday: z
      .boolean()
      .nullable()
      .optional()
      .describe("Whether the place is open today. Recalculated daily.")
      .meta({ example: true }),
    photos: z.array(photoSchema).nullable().optional(),
    placeType: placeTypeEnumSchema
      .nullable()
      .optional()
      .meta({ example: PlaceType.PLACE }),
    services: z
      .array(serviceSchema)
      .nullable()
      .optional()
      .describe("List of services available at the place."),
    position: positionSchema
      .nullable()
      .optional()
      .describe("Address and geographic information of the place."),
    waypoints: z
      .array(parcoursSchema)
      .nullable()
      .optional()
      .describe(
        'Details about the Parcours of a facility when `placeType` is "PARCOURS_MOBILE"'
      ),
    organizationInfo: entitySchema
      .nullable()
      .optional()
      .describe("Organization contact information."),
    openingHours: openingHoursSchema
      .nullable()
      .optional()
      .describe("Opening hours of the place."),
    modalities: modalitiesSchema
      .nullable()
      .optional()
      .describe("Access conditions of the place."),
    publics: publicsSchema
      .nullable()
      .optional()
      .describe("Audience welcomed at the place."),
    country: countryCodesEnumSchema
      .nullable()
      .optional()
      .describe("Country code of the place.")
      .meta({ example: CountryCodes.FR }),
    languages: z
      .array(placeLanguagesEnumSchema)
      .nullable()
      .optional()
      .describe("Languages spoken at the place.")
      .meta({ example: ["fr", "en"] }),
    createdAt: dateSchema
      .nullable()
      .optional()
      .describe("Creation date of the place. Format ISO 8601."),
    updatedAt: dateSchema
      .nullable()
      .optional()
      .describe("Last update date of the place. Format ISO 8601."),
    updatedByUserAt: dateSchema
      .nullable()
      .optional()
      .describe("Last user update date of the place. Format ISO 8601."),
    tempInfo: z
      .looseObject({
        closure: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
          })
          .nullable()
          .optional()
          .describe("Temporary closure of the place."),
        hours: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
            hours: z
              .looseObject({})
              .nullable()
              .optional()
              .describe("Temporary opening hours of the place."),
          })
          .nullable()
          .optional()
          .describe("Temporary opening hours of the place."),
        message: z
          .looseObject({
            active: z
              .boolean()
              .nullable()
              .optional()
              .describe(
                "Indicates whether the temporary information is currently active."
              ),
            startDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "Start date of the temporary information. Format ISO 8601."
              ),
            endDate: z
              .string()
              .nullable()
              .optional()
              .describe(
                "End date of the temporary information. Format ISO 8601."
              ),
            description: z
              .string()
              .nullable()
              .optional()
              .describe("Message describing the temporary information."),
            name: z.string().nullable().optional(),
          })
          .nullable()
          .optional(),
      })
      .nullable()
      .optional()
      .describe("Temporary closure, opening hours and message information."),
    sources: z
      .array(sourceSchema)
      .nullable()
      .optional()
      .describe("External data sources paired with the place."),
    slugs: slugsSchema.nullable().optional(),
    distance: z
      .number()
      .nullable()
      .optional()
      .describe("Distance between the search center and the place, in meters.")
      .meta({ example: 135.87 }),
  })
  .meta({
    id: "v20260426SearchPlaceResponse",
  });

export const v20260426SearchResponseSchema = z
  .object({
    nbResults: z
      .number()
      .int()
      .min(0)
      .nullable()
      .describe("Total number of places matching the request.")
      .meta({ example: 42 }),
    places: z.array(
      z
        .discriminatedUnion("placeType", [
          v20260426SearchPlaceResponseSchema
            .omit({ waypoints: true })
            .extend({
              placeType: z.literal(PlaceType.PLACE),
            })
            .meta({ title: "FixedPosition" }),
          v20260426SearchPlaceResponseSchema
            .omit({ openingHours: true, position: true })
            .extend({
              placeType: z.literal(PlaceType.ITINERARY),
            })
            .meta({ title: "Itinerary" }),
        ])
        .meta({
          discriminator: {
            propertyName: "type",
          },
        })
        .nullable()
        .describe("List of place matching the request.")
    ),
  })
  .meta({ id: "v20260426SearchResponse" });

export type V20260426SearchResponse = z.infer<
  typeof v20260426SearchResponseSchema
>;

export default v20260426SearchResponseSchema;
