/**
 * DO NOT EDIT: This file is generated by search-api artifact generation.
 */
import { z } from "zod";

import { v20260426SearchPlaceResponseSchema } from "./2026-04-26.search-response.schema.generated";

export const v20260426PlaceResponseSchema =
  v20260426SearchPlaceResponseSchema;

export type V20260426PlaceResponse = z.infer<
  typeof v20260426PlaceResponseSchema
>;

export default v20260426PlaceResponseSchema;
