name: _Check commitlint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-commitlint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  commitlint:
    name: Run commitlint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
