# Soliguide: Useful information for those who need it
#
# SPDX-FileCopyrightText: © 2024 Solinum
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: _Test a package

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      container_image:
        type: string
        required: true

jobs:
  test_package:
    name: Test ${{ inputs.package }}
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container_image }}
    permissions:
      packages: read
    defaults:
      run:
        working-directory: /app
    steps:
      - name: Prettier cache
        uses: actions/cache@v4
        with:
          path: packages/${{ inputs.package }}/node_modules/.cache/prettier
          key: ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-prettiercache-${{ inputs.package }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-prettiercache-${{ inputs.package }}-${{ github.base_ref }}
            ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-prettiercache-${{ inputs.package }}-

      - name: Format check
        run: yarn workspace @soliguide/${{ inputs.package }} format

      - name: Eslint cache
        uses: actions/cache@v4
        with:
          path: packages/${{ inputs.package }}/.eslintcache
          key: ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-eslintcache-${{ inputs.package }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-eslintcache-${{ inputs.package }}-${{ github.base_ref }}
            ${{ runner.os }}-${{ needs.affected_packages.outputs.node_version }}-eslintcache-

      - name: Lint
        run: yarn workspace @soliguide/${{ inputs.package }} lint

      - name: Test
        run: yarn workspace @soliguide/${{ inputs.package }} test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.package }}
          path: /app/packages/${{ inputs.package }}/coverage/cobertura-coverage.xml
          if-no-files-found: error
          retention-days: 1
