name: Cron - Cleanup images

on:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete_untagged_container_images:
    name: Delete 31 days old untagged container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          - soliguide/api
          - soliguide/base
          - soliguide/common
          - soliguide/common-angular
          - soliguide/design-system
          - soliguide/frontend
          - soliguide/location-api
          - soliguide/maintenance
          - soliguide/soligare
          - soliguide/web-app
          - soliguide/widget
    steps:
      - name: Delete untagged images of ${{ matrix.package }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ matrix.package }}
          delete-untagged: true
          older-than: 31 days
          token: ${{ secrets.GITHUB_TOKEN }}

  delete_branch_container_images:
    name: Delete 31 days old branch container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          - soliguide/api
          - soliguide/base
          - soliguide/common
          - soliguide/common-angular
          - soliguide/design-system
          - soliguide/frontend
          - soliguide/location-api
          - soliguide/maintenance
          - soliguide/soligare
          - soliguide/web-app
          - soliguide/widget
        tags:
          - develop-*
          # Not yet built
          # - main-*
    steps:
      - name: Delete untagged images of ${{ matrix.package }}
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ matrix.package }}
          delete-tags: ${{ matrix.tags }}
          older-than: 31 days
          token: ${{ secrets.GITHUB_TOKEN }}
