name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (ex: v1.3.0)"
        required: true
        type: string

jobs:
  deploy-prod:
    name: Deploy ${{ inputs.tag }} to production
    uses: ./.github/workflows/_deploy-to-environment.yml
    with:
      environment: production
      tag: ${{ inputs.tag }}
    secrets: inherit
