name: Develop - build and deploy

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all packages (once)
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  deploy_clever_cloud:
    name: Deploy to Clever Cloud (staging)
    uses: ./.github/workflows/_deploy-to-environment.yml
    with:
      environment: staging
    needs:
      - build
    secrets: inherit

  deploy_qovery:
    name: Deploy to Qovery (develop)
    uses: ./.github/workflows/_deploy-to-test-qovery.yml
    with:
      deploy_api: ${{ contains(needs.build.outputs.to_deploy, 'api') }}
      deploy_frontend: ${{ contains(needs.build.outputs.to_deploy, 'frontend') }}
      deploy_location-api: ${{ contains(needs.build.outputs.to_deploy, 'location-api') }}
      deploy_web-app: ${{ contains(needs.build.outputs.to_deploy, 'web-app') }}
      deploy_widget: ${{ contains(needs.build.outputs.to_deploy, 'widget') }}
      create: true
    needs:
      - build
    secrets: inherit
