name: Hotfix - build, test and deploy to staging

on:
  push:
    branches:
      - hotfix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    uses: ./.github/workflows/_commitlint.yml

  build:
    name: Build all packages
    uses: ./.github/workflows/_build.yml
    needs:
      - commitlint
    secrets: inherit

  test:
    name: Test all packages
    uses: ./.github/workflows/_test-only.yml
    with:
      docker_tag: hotfix
      node_version: ${{ needs.build.outputs.node_version }}
      test_api: true
      test_common: true
      test_common-angular: true
      test_design-system: true
      test_frontend: true
      test_location-api: true
      test_maintenance: true
      test_soligare: true
      test_web-app: true
      test_widget: true
    needs:
      - build
    secrets: inherit

  deploy-staging:
    name: Deploy hotfix to staging
    needs:
      - build
      - test
    uses: ./.github/workflows/_deploy-to-environment.yml
    with:
      environment: staging
      tag: hotfix
    secrets: inherit
