name: PR - Autoassign draft status

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  changes_requested:
    if: github.event.review.state == 'changes_requested' && github.event.pull_request.draft == false
    name: Change PR status to draft when a reviewer request changes
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as draft
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation($pullRequestId: ID!) {
              convertPullRequestToDraft(input: { pullRequestId: $pullRequestId }) {
                pullRequest {
                  id
                  number
                  isDraft
                }
              }
            }
          variables: |
            pullRequestId: ${{ github.event.pull_request.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
