name: Test - Develop

on:
  workflow_run:
    workflows:
      - Develop - build and deploy
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  affected_packages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pr-get-affected-packages.yml

  test:
    name: Test all packages (using built images)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_test-only.yml
    with:
      docker_tag: develop
      node_version: ${{ needs.affected_packages.outputs.node_version }}
      test_api: ${{ contains(needs.affected_packages.outputs.to_test, 'api') }}
      test_common: ${{ contains(needs.affected_packages.outputs.to_test, 'common') }}
      test_common-angular: ${{ contains(needs.affected_packages.outputs.to_test, 'common-angular') }}
      test_design-system: ${{ contains(needs.affected_packages.outputs.to_test, 'design-system') }}
      test_frontend: ${{ contains(needs.affected_packages.outputs.to_test, 'frontend') }}
      test_location-api: ${{ contains(needs.affected_packages.outputs.to_test, 'location-api') }}
      test_maintenance: ${{ contains(needs.affected_packages.outputs.to_test, 'maintenance') }}
      test_web-app: ${{ contains(needs.affected_packages.outputs.to_test, 'web-app') }}
      test_widget: ${{ contains(needs.affected_packages.outputs.to_test, 'widget') }}
    needs:
      - affected_packages
    secrets: inherit
